/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/branch/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["branch_list"];
        put?: never;
        post: operations["branch_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/branch/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["branch_retrieve"];
        put: operations["branch_update"];
        post?: never;
        delete: operations["branch_destroy"];
        options?: never;
        head?: never;
        patch: operations["branch_partial_update"];
        trace?: never;
    };
    "/v1/category/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["category_list"];
        put?: never;
        post: operations["category_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/category/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["category_retrieve"];
        put: operations["category_update"];
        post?: never;
        delete: operations["category_destroy"];
        options?: never;
        head?: never;
        patch: operations["category_partial_update"];
        trace?: never;
    };
    "/v1/company/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["company_retrieve"];
        put: operations["company_update"];
        post: operations["company_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["company_partial_update"];
        trace?: never;
    };
    "/v1/customers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["customers_list"];
        put?: never;
        post: operations["customers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["customers_retrieve"];
        put: operations["customers_update"];
        post?: never;
        delete: operations["customers_destroy"];
        options?: never;
        head?: never;
        patch: operations["customers_partial_update"];
        trace?: never;
    };
    "/v1/exchange-rates/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exchange_rates_history_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exchange-rates/today/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exchange_rates_today_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/measurement/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["measurement_list"];
        put?: never;
        post: operations["measurement_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/measurement/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["measurement_retrieve"];
        put: operations["measurement_update"];
        post?: never;
        delete: operations["measurement_destroy"];
        options?: never;
        head?: never;
        patch: operations["measurement_partial_update"];
        trace?: never;
    };
    "/v1/product/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["product_list"];
        put?: never;
        post: operations["product_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/product-branch-stock/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["product_branch_stock_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/product/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["product_retrieve"];
        put: operations["product_update"];
        post?: never;
        delete: operations["product_destroy"];
        options?: never;
        head?: never;
        patch: operations["product_partial_update"];
        trace?: never;
    };
    "/v1/providers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["providers_list"];
        put?: never;
        post: operations["providers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["providers_retrieve"];
        put: operations["providers_update"];
        post?: never;
        delete: operations["providers_destroy"];
        options?: never;
        head?: never;
        patch: operations["providers_partial_update"];
        trace?: never;
    };
    "/v1/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sales/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List all sales or create a new sale.
         *     Supports nested creation of sale details.
         */
        get: operations["sales_list"];
        put?: never;
        /**
         * @description List all sales or create a new sale.
         *     Supports nested creation of sale details.
         */
        post: operations["sales_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sales/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Retrieve, update, or delete a sale.
         *     Delete operation is soft delete (sets state=False).
         */
        get: operations["sales_retrieve"];
        /**
         * @description Retrieve, update, or delete a sale.
         *     Delete operation is soft delete (sets state=False).
         */
        put: operations["sales_update"];
        post?: never;
        /**
         * @description Retrieve, update, or delete a sale.
         *     Delete operation is soft delete (sets state=False).
         */
        delete: operations["sales_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Retrieve, update, or delete a sale.
         *     Delete operation is soft delete (sets state=False).
         */
        patch: operations["sales_partial_update"];
        trace?: never;
    };
    "/v1/sales/{sale_id}/payments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List payments for a sale or create a new payment.
         *     Nested under /sales/<sale_id>/payments/
         */
        get: operations["sales_payments_list"];
        put?: never;
        /**
         * @description List payments for a sale or create a new payment.
         *     Nested under /sales/<sale_id>/payments/
         */
        post: operations["sales_payments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user-branches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_branches_retrieve"];
        put: operations["user_branches_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user-info/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_info_retrieve"];
        put: operations["user_info_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["user_info_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Branch: {
            name: string;
            address?: string | null;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            /** Format: uuid */
            readonly id: string;
        };
        BranchRequest: {
            name: string;
            address?: string | null;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
        };
        Category: {
            name: string;
            /** Format: uuid */
            readonly id: string;
        };
        CategoryRequest: {
            name: string;
        };
        Company: {
            name: string;
            /** Format: email */
            email: string;
            max_branches: number;
            /** Format: date */
            license_date: string;
            /** Format: uuid */
            readonly id: string;
        };
        CompanyRequest: {
            name: string;
            /** Format: email */
            email: string;
            max_branches: number;
            /** Format: date */
            license_date: string;
        };
        CustomUser: {
            /** Format: email */
            email: string;
            first_name?: string;
            last_name?: string;
            /** Format: uuid */
            company_id: string;
            branch_ids?: string[];
        };
        CustomUserRequest: {
            /** Format: email */
            email: string;
            first_name?: string;
            last_name?: string;
            /** Format: uuid */
            company_id: string;
            branch_ids?: string[];
        };
        Customer: {
            /** Format: uuid */
            readonly id: string;
            readonly company: components["schemas"]["Company"];
            /** Format: date-time */
            readonly created_at: string;
            name: string;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            document?: string | null;
            changed_by?: number | null;
        };
        CustomerRequest: {
            name: string;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            document?: string | null;
            changed_by?: number | null;
        };
        MeasurementUnit: {
            name: string;
            decimals?: boolean;
            /** Format: uuid */
            readonly id: string;
        };
        MeasurementUnitRequest: {
            name: string;
            decimals?: boolean;
        };
        PatchedBranchRequest: {
            name?: string;
            address?: string | null;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
        };
        PatchedCategoryRequest: {
            name?: string;
        };
        PatchedCompanyRequest: {
            name?: string;
            /** Format: email */
            email?: string;
            max_branches?: number;
            /** Format: date */
            license_date?: string;
        };
        PatchedCustomUserRequest: {
            /** Format: email */
            email?: string;
            first_name?: string;
            last_name?: string;
            /** Format: uuid */
            company_id?: string;
            branch_ids?: string[];
        };
        PatchedCustomerRequest: {
            name?: string;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            document?: string | null;
            changed_by?: number | null;
        };
        PatchedMeasurementUnitRequest: {
            name?: string;
            decimals?: boolean;
        };
        PatchedProductMasterRequest: {
            name?: string;
            description?: string | null;
            /** Format: decimal */
            cost_price_usd?: string;
            /** Format: decimal */
            profit_margin?: string;
            IVA?: boolean;
            /** Format: uuid */
            category?: string | null;
            /** Format: uuid */
            measurement_unit?: string | null;
        };
        PatchedProviderRequest: {
            name?: string;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            document?: string | null;
            changed_by?: number | null;
        };
        /**
         * @description Main serializer for creating and viewing sales.
         *     Supports nested creation of sale details.
         */
        PatchedSaleRequest: {
            /** Format: uuid */
            branch?: string;
            /** Format: uuid */
            customer?: string | null;
            /** @description List of sale details with 'product' (ULID) and 'quantity' fields */
            details?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * @description * `PENDING` - Pending
         *     * `PARTIALLY_PAID` - Partially Paid
         *     * `PAID` - Paid
         *     * `OVERPAID` - Overpaid
         * @enum {string}
         */
        PaymentStatusEnum: "PENDING" | "PARTIALLY_PAID" | "PAID" | "OVERPAID";
        ProductMaster: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            description?: string | null;
            /** Format: decimal */
            cost_price_usd: string;
            /** Format: decimal */
            profit_margin: string;
            IVA?: boolean;
            /** Format: uuid */
            category?: string | null;
            /** Format: uuid */
            measurement_unit?: string | null;
        };
        ProductMasterRequest: {
            name: string;
            description?: string | null;
            /** Format: decimal */
            cost_price_usd: string;
            /** Format: decimal */
            profit_margin: string;
            IVA?: boolean;
            /** Format: uuid */
            category?: string | null;
            /** Format: uuid */
            measurement_unit?: string | null;
        };
        ProductStockSale: {
            readonly product_id: string;
            /** Format: decimal */
            stock: string;
        };
        Provider: {
            /** Format: uuid */
            readonly id: string;
            readonly company: components["schemas"]["Company"];
            /** Format: date-time */
            readonly created_at: string;
            name: string;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            document?: string | null;
            changed_by?: number | null;
        };
        ProviderRequest: {
            name: string;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            document?: string | null;
            changed_by?: number | null;
        };
        RegisterUser: {
            /** Format: email */
            email: string;
            first_name?: string;
            last_name?: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
        };
        RegisterUserRequest: {
            /** Format: email */
            email: string;
            password: string;
            /** Format: uuid */
            company_id: string;
            branch_ids?: string[];
            first_name?: string;
            last_name?: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
        };
        /**
         * @description Main serializer for creating and viewing sales.
         *     Supports nested creation of sale details.
         */
        Sale: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            branch: string;
            readonly branch_name: string;
            /** Format: uuid */
            customer?: string | null;
            /** @default Walk-in Customer */
            readonly customer_name: string;
            /** Format: decimal */
            readonly total_amount_usd: string | null;
            readonly payment_status: components["schemas"]["PaymentStatusEnum"];
            readonly seq_number: number;
            readonly sale_details: components["schemas"]["SaleDetail"][];
            readonly total_paid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description Serializer for SaleDetail - used for reading sale details.
         *     For writing, use the nested 'details' field in SaleSerializer.
         */
        SaleDetail: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            product: string;
            readonly product_name: string;
            /** Format: double */
            quantity: number;
            /** Format: decimal */
            readonly unit_price: string;
        };
        /**
         * @description Serializer for SaleDetail - used for reading sale details.
         *     For writing, use the nested 'details' field in SaleSerializer.
         */
        SaleDetailRequest: {
            /** Format: uuid */
            product: string;
            /** Format: double */
            quantity: number;
        };
        /**
         * @description Lightweight serializer for listing sales.
         *     Includes computed fields for display purposes.
         */
        SaleList: {
            /** Format: uuid */
            readonly id: string;
            readonly seq_number: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: decimal */
            readonly total_amount_usd: string | null;
            readonly payment_status: components["schemas"]["PaymentStatusEnum"];
            /** Format: uuid */
            readonly branch: string;
            readonly branch_name: string;
            /** Format: uuid */
            readonly customer: string | null;
            /** @default Walk-in Customer */
            readonly customer_name: string;
            readonly total_paid: string;
        };
        /**
         * @description Serializer for creating and viewing sale payments.
         *     Handles currency conversion and payment status updates.
         */
        SalePayment: {
            /** Format: uuid */
            readonly id: string;
            currency: string;
            payment_method: string;
            /** Format: date-time */
            readonly payment_date: string;
            /** Format: decimal */
            discount: string;
            /** Format: decimal */
            readonly total_amount_usd: string;
            /** Format: decimal */
            readonly total_amount_ves: string;
            /** Format: uuid */
            readonly exchange_rate: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description Serializer for creating and viewing sale payments.
         *     Handles currency conversion and payment status updates.
         */
        SalePaymentRequest: {
            currency: string;
            payment_method: string;
            /** Format: decimal */
            discount: string;
            /**
             * Format: decimal
             * @description Payment amount in the specified currency
             */
            amount: string;
        };
        /**
         * @description Main serializer for creating and viewing sales.
         *     Supports nested creation of sale details.
         */
        SaleRequest: {
            /** Format: uuid */
            branch: string;
            /** Format: uuid */
            customer?: string | null;
            /** @description List of sale details with 'product' (ULID) and 'quantity' fields */
            details: {
                [key: string]: unknown;
            }[];
        };
        TokenRefresh: {
            readonly access: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    branch_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"][];
                };
            };
        };
    };
    branch_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BranchRequest"];
                "multipart/form-data": components["schemas"]["BranchRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"];
                };
            };
        };
    };
    branch_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"];
                };
            };
        };
    };
    branch_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BranchRequest"];
                "multipart/form-data": components["schemas"]["BranchRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"];
                };
            };
        };
    };
    branch_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    branch_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBranchRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBranchRequest"];
                "multipart/form-data": components["schemas"]["PatchedBranchRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"];
                };
            };
        };
    };
    category_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    category_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CategoryRequest"];
                "multipart/form-data": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    category_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    category_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CategoryRequest"];
                "multipart/form-data": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    category_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    category_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCategoryRequest"];
                "multipart/form-data": components["schemas"]["PatchedCategoryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    company_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
        };
    };
    company_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CompanyRequest"];
                "multipart/form-data": components["schemas"]["CompanyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
        };
    };
    company_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CompanyRequest"];
                "multipart/form-data": components["schemas"]["CompanyRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
        };
    };
    company_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCompanyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCompanyRequest"];
                "multipart/form-data": components["schemas"]["PatchedCompanyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
        };
    };
    customers_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"][];
                };
            };
        };
    };
    customers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomerRequest"];
                "multipart/form-data": components["schemas"]["CustomerRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    customers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    customers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomerRequest"];
                "multipart/form-data": components["schemas"]["CustomerRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    customers_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    customers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCustomerRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCustomerRequest"];
                "multipart/form-data": components["schemas"]["PatchedCustomerRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    exchange_rates_history_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exchange_rates_today_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    measurement_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementUnit"][];
                };
            };
        };
    };
    measurement_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeasurementUnitRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MeasurementUnitRequest"];
                "multipart/form-data": components["schemas"]["MeasurementUnitRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementUnit"];
                };
            };
        };
    };
    measurement_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementUnit"];
                };
            };
        };
    };
    measurement_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeasurementUnitRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MeasurementUnitRequest"];
                "multipart/form-data": components["schemas"]["MeasurementUnitRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementUnit"];
                };
            };
        };
    };
    measurement_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    measurement_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMeasurementUnitRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMeasurementUnitRequest"];
                "multipart/form-data": components["schemas"]["PatchedMeasurementUnitRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementUnit"];
                };
            };
        };
    };
    product_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductMaster"][];
                };
            };
        };
    };
    product_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductMasterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductMasterRequest"];
                "multipart/form-data": components["schemas"]["ProductMasterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductMaster"];
                };
            };
        };
    };
    product_branch_stock_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductStockSale"][];
                };
            };
        };
    };
    product_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductMaster"];
                };
            };
        };
    };
    product_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductMasterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductMasterRequest"];
                "multipart/form-data": components["schemas"]["ProductMasterRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductMaster"];
                };
            };
        };
    };
    product_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    product_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProductMasterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProductMasterRequest"];
                "multipart/form-data": components["schemas"]["PatchedProductMasterRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductMaster"];
                };
            };
        };
    };
    providers_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"][];
                };
            };
        };
    };
    providers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProviderRequest"];
                "multipart/form-data": components["schemas"]["ProviderRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
        };
    };
    providers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
        };
    };
    providers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProviderRequest"];
                "multipart/form-data": components["schemas"]["ProviderRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
        };
    };
    providers_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    providers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProviderRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProviderRequest"];
                "multipart/form-data": components["schemas"]["PatchedProviderRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
        };
    };
    refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterUserRequest"];
                "multipart/form-data": components["schemas"]["RegisterUserRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterUser"];
                };
            };
        };
    };
    sales_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleList"][];
                };
            };
        };
    };
    sales_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaleRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SaleRequest"];
                "multipart/form-data": components["schemas"]["SaleRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sale"];
                };
            };
        };
    };
    sales_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sale"];
                };
            };
        };
    };
    sales_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaleRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SaleRequest"];
                "multipart/form-data": components["schemas"]["SaleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sale"];
                };
            };
        };
    };
    sales_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sales_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSaleRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSaleRequest"];
                "multipart/form-data": components["schemas"]["PatchedSaleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sale"];
                };
            };
        };
    };
    sales_payments_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sale_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalePayment"][];
                };
            };
        };
    };
    sales_payments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sale_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalePaymentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SalePaymentRequest"];
                "multipart/form-data": components["schemas"]["SalePaymentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalePayment"];
                };
            };
        };
    };
    user_branches_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_branches_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_info_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomUser"];
                };
            };
        };
    };
    user_info_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomUserRequest"];
                "multipart/form-data": components["schemas"]["CustomUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomUser"];
                };
            };
        };
    };
    user_info_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCustomUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCustomUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedCustomUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomUser"];
                };
            };
        };
    };
}
