// This file is auto-generated by @hey-api/openapi-ts

export const AccountSchema = {
    type: 'object',
    description: 'Main serializer for creating and viewing accounts (purchases).\nSupports nested creation of account details.\nIncreases stock when account is created.',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        branch: {
            type: 'string',
            format: 'uuid'
        },
        branch_name: {
            type: 'string',
            readOnly: true
        },
        provider: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        provider_name: {
            type: 'string',
            readOnly: true,
            default: 'No Provider'
        },
        total_amount_usd: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
            readOnly: true,
            nullable: true
        },
        payment_status: {
            allOf: [
                {
                    $ref: '#/components/schemas/PaymentStatus2d7Enum'
                }
            ],
            readOnly: true
        },
        seq_number: {
            type: 'integer',
            readOnly: true
        },
        account_details: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/AccountDetail'
            },
            readOnly: true
        },
        total_paid: {
            type: 'string',
            readOnly: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: [
        'account_details',
        'branch',
        'branch_name',
        'created_at',
        'id',
        'payment_status',
        'provider_name',
        'seq_number',
        'total_amount_usd',
        'total_paid',
        'updated_at'
    ]
} as const;

export const AccountDetailSchema = {
    type: 'object',
    description: 'Serializer for AccountDetail - used for reading account details.\nFor writing, use the nested \'details\' field in AccountSerializer.',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        product: {
            type: 'string',
            format: 'uuid'
        },
        product_name: {
            type: 'string',
            readOnly: true
        },
        quantity: {
            type: 'number',
            format: 'double'
        },
        unit_price: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
            readOnly: true
        }
    },
    required: [
        'id',
        'product',
        'product_name',
        'quantity',
        'unit_price'
    ]
} as const;

export const AccountDetailRequestSchema = {
    type: 'object',
    description: 'Serializer for AccountDetail - used for reading account details.\nFor writing, use the nested \'details\' field in AccountSerializer.',
    properties: {
        product: {
            type: 'string',
            format: 'uuid'
        },
        quantity: {
            type: 'number',
            format: 'double'
        }
    },
    required: [
        'product',
        'quantity'
    ]
} as const;

export const AccountListSchema = {
    type: 'object',
    description: 'Lightweight serializer for listing accounts.\nIncludes computed fields for display purposes.',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        seq_number: {
            type: 'integer',
            readOnly: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        total_amount_usd: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
            readOnly: true,
            nullable: true
        },
        payment_status: {
            allOf: [
                {
                    $ref: '#/components/schemas/PaymentStatus2d7Enum'
                }
            ],
            readOnly: true
        },
        branch: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        branch_name: {
            type: 'string',
            readOnly: true
        },
        provider: {
            type: 'string',
            format: 'uuid',
            readOnly: true,
            nullable: true
        },
        provider_name: {
            type: 'string',
            readOnly: true,
            default: 'No Provider'
        },
        total_paid: {
            type: 'string',
            readOnly: true
        }
    },
    required: [
        'branch',
        'branch_name',
        'created_at',
        'id',
        'payment_status',
        'provider',
        'provider_name',
        'seq_number',
        'total_amount_usd',
        'total_paid',
        'updated_at'
    ]
} as const;

export const AccountPaymentSchema = {
    type: 'object',
    description: 'Serializer for creating and viewing account payments.\nHandles currency conversion and payment status updates.',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        currency: {
            type: 'string',
            maxLength: 3
        },
        payment_method: {
            type: 'string'
        },
        payment_date: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        REF: {
            type: 'string',
            nullable: true,
            maxLength: 100
        },
        total_amount_usd: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
            readOnly: true
        },
        total_amount_ves: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
            readOnly: true
        },
        exchange_rate: {
            type: 'string',
            format: 'uuid',
            readOnly: true,
            nullable: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: [
        'created_at',
        'currency',
        'exchange_rate',
        'id',
        'payment_date',
        'payment_method',
        'total_amount_usd',
        'total_amount_ves'
    ]
} as const;

export const AccountPaymentRequestSchema = {
    type: 'object',
    description: 'Serializer for creating and viewing account payments.\nHandles currency conversion and payment status updates.',
    properties: {
        currency: {
            type: 'string',
            minLength: 1,
            maxLength: 3
        },
        payment_method: {
            type: 'string',
            minLength: 1
        },
        REF: {
            type: 'string',
            nullable: true,
            maxLength: 100
        }
    },
    required: [
        'currency',
        'payment_method'
    ]
} as const;

export const AccountRequestSchema = {
    type: 'object',
    description: 'Main serializer for creating and viewing accounts (purchases).\nSupports nested creation of account details.\nIncreases stock when account is created.',
    properties: {
        branch: {
            type: 'string',
            format: 'uuid'
        },
        provider: {
            type: 'string',
            format: 'uuid',
            nullable: true
        }
    },
    required: [
        'branch'
    ]
} as const;

export const BranchSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            maxLength: 200
        },
        address: {
            type: 'string',
            nullable: true,
            maxLength: 200
        },
        phone: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 200
        },
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        }
    },
    required: [
        'id',
        'name'
    ]
} as const;

export const BranchRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 200
        },
        address: {
            type: 'string',
            nullable: true,
            maxLength: 200
        },
        phone: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 200
        }
    },
    required: [
        'name'
    ]
} as const;

export const CategorySchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            maxLength: 200
        },
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        }
    },
    required: [
        'id',
        'name'
    ]
} as const;

export const CategoryRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 200
        }
    },
    required: [
        'name'
    ]
} as const;

export const CompanySchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            maxLength: 100
        },
        email: {
            type: 'string',
            format: 'email',
            maxLength: 200
        },
        max_branches: {
            type: 'integer',
            maximum: 2147483647,
            minimum: 0
        },
        license_date: {
            type: 'string',
            format: 'date'
        },
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        }
    },
    required: [
        'email',
        'id',
        'license_date',
        'max_branches',
        'name'
    ]
} as const;

export const CompanyRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 100
        },
        email: {
            type: 'string',
            format: 'email',
            minLength: 1,
            maxLength: 200
        },
        max_branches: {
            type: 'integer',
            maximum: 2147483647,
            minimum: 0
        },
        license_date: {
            type: 'string',
            format: 'date'
        }
    },
    required: [
        'email',
        'license_date',
        'max_branches',
        'name'
    ]
} as const;

export const CustomUserSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email',
            maxLength: 254
        },
        first_name: {
            type: 'string',
            maxLength: 150
        },
        last_name: {
            type: 'string',
            maxLength: 150
        },
        company_id: {
            type: 'string',
            format: 'uuid'
        },
        branch_ids: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    },
    required: [
        'company_id',
        'email'
    ]
} as const;

export const CustomUserRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email',
            minLength: 1,
            maxLength: 254
        },
        first_name: {
            type: 'string',
            maxLength: 150
        },
        last_name: {
            type: 'string',
            maxLength: 150
        },
        company_id: {
            type: 'string',
            format: 'uuid'
        },
        branch_ids: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    },
    required: [
        'company_id',
        'email'
    ]
} as const;

export const CustomerSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        company: {
            allOf: [
                {
                    $ref: '#/components/schemas/Company'
                }
            ],
            readOnly: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        phone: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 200
        },
        document: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        changed_by: {
            type: 'integer',
            nullable: true
        }
    },
    required: [
        'company',
        'created_at',
        'id',
        'name'
    ]
} as const;

export const CustomerRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 200
        },
        phone: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 200
        },
        document: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        changed_by: {
            type: 'integer',
            nullable: true
        }
    },
    required: [
        'name'
    ]
} as const;

export const MeasurementUnitSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            maxLength: 200
        },
        decimals: {
            type: 'boolean'
        },
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        }
    },
    required: [
        'id',
        'name'
    ]
} as const;

export const MeasurementUnitRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 200
        },
        decimals: {
            type: 'boolean'
        }
    },
    required: [
        'name'
    ]
} as const;

export const PatchedAccountRequestSchema = {
    type: 'object',
    description: 'Main serializer for creating and viewing accounts (purchases).\nSupports nested creation of account details.\nIncreases stock when account is created.',
    properties: {
        branch: {
            type: 'string',
            format: 'uuid'
        },
        provider: {
            type: 'string',
            format: 'uuid',
            nullable: true
        }
    }
} as const;

export const PatchedBranchRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 200
        },
        address: {
            type: 'string',
            nullable: true,
            maxLength: 200
        },
        phone: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 200
        }
    }
} as const;

export const PatchedCategoryRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 200
        }
    }
} as const;

export const PatchedCompanyRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 100
        },
        email: {
            type: 'string',
            format: 'email',
            minLength: 1,
            maxLength: 200
        },
        max_branches: {
            type: 'integer',
            maximum: 2147483647,
            minimum: 0
        },
        license_date: {
            type: 'string',
            format: 'date'
        }
    }
} as const;

export const PatchedCustomUserRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email',
            minLength: 1,
            maxLength: 254
        },
        first_name: {
            type: 'string',
            maxLength: 150
        },
        last_name: {
            type: 'string',
            maxLength: 150
        },
        company_id: {
            type: 'string',
            format: 'uuid'
        },
        branch_ids: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const PatchedCustomerRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 200
        },
        phone: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 200
        },
        document: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        changed_by: {
            type: 'integer',
            nullable: true
        }
    }
} as const;

export const PatchedMeasurementUnitRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 200
        },
        decimals: {
            type: 'boolean'
        }
    }
} as const;

export const PatchedProductMasterRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 200
        },
        description: {
            type: 'string',
            nullable: true
        },
        cost_price_usd: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$'
        },
        profit_margin: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,3}(?:\\.\\d{0,2})?$'
        },
        IVA: {
            type: 'boolean'
        },
        category: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        measurement_unit: {
            type: 'string',
            format: 'uuid',
            nullable: true
        }
    }
} as const;

export const PatchedProviderRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 200
        },
        phone: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 200
        },
        document: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        changed_by: {
            type: 'integer',
            nullable: true
        }
    }
} as const;

export const PatchedSaleRequestSchema = {
    type: 'object',
    description: 'Main serializer for creating and viewing sales.\nSupports nested creation of sale details.',
    properties: {
        branch: {
            type: 'string',
            format: 'uuid'
        },
        customer: {
            type: 'string',
            format: 'uuid',
            nullable: true
        }
    }
} as const;

export const PaymentStatus2d7EnumSchema = {
    enum: [
        'PENDING',
        'PARTIALLY_PAID',
        'PAID'
    ],
    type: 'string',
    description: '* `PENDING` - Pending\n* `PARTIALLY_PAID` - Partially Paid\n* `PAID` - Paid'
} as const;

export const PaymentStatusAb7EnumSchema = {
    enum: [
        'PENDING',
        'PARTIALLY_PAID',
        'PAID',
        'OVERPAID'
    ],
    type: 'string',
    description: '* `PENDING` - Pending\n* `PARTIALLY_PAID` - Partially Paid\n* `PAID` - Paid\n* `OVERPAID` - Overpaid'
} as const;

export const ProductMasterSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        description: {
            type: 'string',
            nullable: true
        },
        cost_price_usd: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$'
        },
        profit_margin: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,3}(?:\\.\\d{0,2})?$'
        },
        IVA: {
            type: 'boolean'
        },
        category: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        measurement_unit: {
            type: 'string',
            format: 'uuid',
            nullable: true
        }
    },
    required: [
        'cost_price_usd',
        'id',
        'name',
        'profit_margin'
    ]
} as const;

export const ProductMasterRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 200
        },
        description: {
            type: 'string',
            nullable: true
        },
        cost_price_usd: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$'
        },
        profit_margin: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,3}(?:\\.\\d{0,2})?$'
        },
        IVA: {
            type: 'boolean'
        },
        category: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        measurement_unit: {
            type: 'string',
            format: 'uuid',
            nullable: true
        }
    },
    required: [
        'cost_price_usd',
        'name',
        'profit_margin'
    ]
} as const;

export const ProductStockSaleSchema = {
    type: 'object',
    properties: {
        product_id: {
            type: 'string',
            readOnly: true
        },
        stock: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,6}(?:\\.\\d{0,4})?$'
        }
    },
    required: [
        'product_id',
        'stock'
    ]
} as const;

export const ProviderSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        company: {
            allOf: [
                {
                    $ref: '#/components/schemas/Company'
                }
            ],
            readOnly: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        phone: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 200
        },
        document: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        changed_by: {
            type: 'integer',
            nullable: true
        }
    },
    required: [
        'company',
        'created_at',
        'id',
        'name'
    ]
} as const;

export const ProviderRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            maxLength: 200
        },
        phone: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 200
        },
        document: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        changed_by: {
            type: 'integer',
            nullable: true
        }
    },
    required: [
        'name'
    ]
} as const;

export const RegisterUserSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email',
            maxLength: 254
        },
        first_name: {
            type: 'string',
            maxLength: 150
        },
        last_name: {
            type: 'string',
            maxLength: 150
        },
        username: {
            type: 'string',
            description: 'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
            pattern: '^[\\w.@+-]+$',
            maxLength: 150
        }
    },
    required: [
        'email',
        'username'
    ]
} as const;

export const RegisterUserRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email',
            minLength: 1,
            maxLength: 254
        },
        first_name: {
            type: 'string',
            maxLength: 150
        },
        last_name: {
            type: 'string',
            maxLength: 150
        },
        username: {
            type: 'string',
            minLength: 1,
            description: 'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
            pattern: '^[\\w.@+-]+$',
            maxLength: 150
        }
    },
    required: [
        'email',
        'username'
    ]
} as const;

export const SaleSchema = {
    type: 'object',
    description: 'Main serializer for creating and viewing sales.\nSupports nested creation of sale details.',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        branch: {
            type: 'string',
            format: 'uuid'
        },
        branch_name: {
            type: 'string',
            readOnly: true
        },
        customer: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        customer_name: {
            type: 'string',
            readOnly: true,
            default: 'Walk-in Customer'
        },
        total_amount_usd: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
            readOnly: true,
            nullable: true
        },
        payment_status: {
            allOf: [
                {
                    $ref: '#/components/schemas/PaymentStatusAb7Enum'
                }
            ],
            readOnly: true
        },
        seq_number: {
            type: 'integer',
            readOnly: true
        },
        sale_details: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/SaleDetail'
            },
            readOnly: true
        },
        total_paid: {
            type: 'string',
            readOnly: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: [
        'branch',
        'branch_name',
        'created_at',
        'customer_name',
        'id',
        'payment_status',
        'sale_details',
        'seq_number',
        'total_amount_usd',
        'total_paid',
        'updated_at'
    ]
} as const;

export const SaleDetailSchema = {
    type: 'object',
    description: 'Serializer for SaleDetail - used for reading sale details.\nFor writing, use the nested \'details\' field in SaleSerializer.',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        product: {
            type: 'string',
            format: 'uuid'
        },
        product_name: {
            type: 'string',
            readOnly: true
        },
        quantity: {
            type: 'number',
            format: 'double'
        },
        unit_price: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
            readOnly: true
        }
    },
    required: [
        'id',
        'product',
        'product_name',
        'quantity',
        'unit_price'
    ]
} as const;

export const SaleDetailRequestSchema = {
    type: 'object',
    description: 'Serializer for SaleDetail - used for reading sale details.\nFor writing, use the nested \'details\' field in SaleSerializer.',
    properties: {
        product: {
            type: 'string',
            format: 'uuid'
        },
        quantity: {
            type: 'number',
            format: 'double'
        }
    },
    required: [
        'product',
        'quantity'
    ]
} as const;

export const SaleListSchema = {
    type: 'object',
    description: 'Lightweight serializer for listing sales.\nIncludes computed fields for display purposes.',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        seq_number: {
            type: 'integer',
            readOnly: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        total_amount_usd: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
            readOnly: true,
            nullable: true
        },
        payment_status: {
            allOf: [
                {
                    $ref: '#/components/schemas/PaymentStatusAb7Enum'
                }
            ],
            readOnly: true
        },
        branch: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        branch_name: {
            type: 'string',
            readOnly: true
        },
        customer: {
            type: 'string',
            format: 'uuid',
            readOnly: true,
            nullable: true
        },
        customer_name: {
            type: 'string',
            readOnly: true,
            default: 'Walk-in Customer'
        },
        total_paid: {
            type: 'string',
            readOnly: true
        }
    },
    required: [
        'branch',
        'branch_name',
        'created_at',
        'customer',
        'customer_name',
        'id',
        'payment_status',
        'seq_number',
        'total_amount_usd',
        'total_paid',
        'updated_at'
    ]
} as const;

export const SalePaymentSchema = {
    type: 'object',
    description: 'Serializer for creating and viewing sale payments.\nHandles currency conversion and payment status updates.',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        currency: {
            type: 'string',
            maxLength: 3
        },
        payment_method: {
            type: 'string'
        },
        payment_date: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        discount: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$'
        },
        total_amount_usd: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
            readOnly: true
        },
        total_amount_ves: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
            readOnly: true
        },
        exchange_rate: {
            type: 'string',
            format: 'uuid',
            readOnly: true,
            nullable: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: [
        'created_at',
        'currency',
        'discount',
        'exchange_rate',
        'id',
        'payment_date',
        'payment_method',
        'total_amount_usd',
        'total_amount_ves'
    ]
} as const;

export const SalePaymentRequestSchema = {
    type: 'object',
    description: 'Serializer for creating and viewing sale payments.\nHandles currency conversion and payment status updates.',
    properties: {
        currency: {
            type: 'string',
            minLength: 1,
            maxLength: 3
        },
        payment_method: {
            type: 'string',
            minLength: 1
        },
        discount: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$'
        }
    },
    required: [
        'currency',
        'discount',
        'payment_method'
    ]
} as const;

export const SaleRequestSchema = {
    type: 'object',
    description: 'Main serializer for creating and viewing sales.\nSupports nested creation of sale details.',
    properties: {
        branch: {
            type: 'string',
            format: 'uuid'
        },
        customer: {
            type: 'string',
            format: 'uuid',
            nullable: true
        }
    },
    required: [
        'branch'
    ]
} as const;

export const TokenRefreshSchema = {
    type: 'object',
    properties: {
        access: {
            type: 'string',
            readOnly: true
        }
    },
    required: [
        'access'
    ]
} as const;

export const TokenRefreshRequestSchema = {
    type: 'object',
    properties: {
        refresh: {
            type: 'string',
            writeOnly: true,
            minLength: 1
        }
    },
    required: [
        'refresh'
    ]
} as const;

export const AccountWritableSchema = {
    type: 'object',
    description: 'Main serializer for creating and viewing accounts (purchases).\nSupports nested creation of account details.\nIncreases stock when account is created.',
    properties: {
        branch: {
            type: 'string',
            format: 'uuid'
        },
        provider: {
            type: 'string',
            format: 'uuid',
            nullable: true
        }
    },
    required: [
        'branch'
    ]
} as const;

export const AccountDetailWritableSchema = {
    type: 'object',
    description: 'Serializer for AccountDetail - used for reading account details.\nFor writing, use the nested \'details\' field in AccountSerializer.',
    properties: {
        product: {
            type: 'string',
            format: 'uuid'
        },
        quantity: {
            type: 'number',
            format: 'double'
        }
    },
    required: [
        'product',
        'quantity'
    ]
} as const;

export const AccountPaymentWritableSchema = {
    type: 'object',
    description: 'Serializer for creating and viewing account payments.\nHandles currency conversion and payment status updates.',
    properties: {
        currency: {
            type: 'string',
            maxLength: 3
        },
        payment_method: {
            type: 'string'
        },
        REF: {
            type: 'string',
            nullable: true,
            maxLength: 100
        }
    },
    required: [
        'currency',
        'payment_method'
    ]
} as const;

export const AccountPaymentRequestWritableSchema = {
    type: 'object',
    description: 'Serializer for creating and viewing account payments.\nHandles currency conversion and payment status updates.',
    properties: {
        currency: {
            type: 'string',
            minLength: 1,
            maxLength: 3
        },
        payment_method: {
            type: 'string',
            minLength: 1
        },
        REF: {
            type: 'string',
            nullable: true,
            maxLength: 100
        },
        amount: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
            writeOnly: true,
            description: 'Payment amount in the specified currency'
        }
    },
    required: [
        'amount',
        'currency',
        'payment_method'
    ]
} as const;

export const AccountRequestWritableSchema = {
    type: 'object',
    description: 'Main serializer for creating and viewing accounts (purchases).\nSupports nested creation of account details.\nIncreases stock when account is created.',
    properties: {
        branch: {
            type: 'string',
            format: 'uuid'
        },
        provider: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        details: {
            type: 'array',
            items: {
                type: 'object',
                additionalProperties: {}
            },
            writeOnly: true,
            description: 'List of account details with \'product\' (ULID) and \'quantity\' fields'
        }
    },
    required: [
        'branch',
        'details'
    ]
} as const;

export const BranchWritableSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            maxLength: 200
        },
        address: {
            type: 'string',
            nullable: true,
            maxLength: 200
        },
        phone: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 200
        }
    },
    required: [
        'name'
    ]
} as const;

export const CategoryWritableSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            maxLength: 200
        }
    },
    required: [
        'name'
    ]
} as const;

export const CompanyWritableSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            maxLength: 100
        },
        email: {
            type: 'string',
            format: 'email',
            maxLength: 200
        },
        max_branches: {
            type: 'integer',
            maximum: 2147483647,
            minimum: 0
        },
        license_date: {
            type: 'string',
            format: 'date'
        }
    },
    required: [
        'email',
        'license_date',
        'max_branches',
        'name'
    ]
} as const;

export const CustomerWritableSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            maxLength: 200
        },
        phone: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 200
        },
        document: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        changed_by: {
            type: 'integer',
            nullable: true
        }
    },
    required: [
        'name'
    ]
} as const;

export const MeasurementUnitWritableSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            maxLength: 200
        },
        decimals: {
            type: 'boolean'
        }
    },
    required: [
        'name'
    ]
} as const;

export const PatchedAccountRequestWritableSchema = {
    type: 'object',
    description: 'Main serializer for creating and viewing accounts (purchases).\nSupports nested creation of account details.\nIncreases stock when account is created.',
    properties: {
        branch: {
            type: 'string',
            format: 'uuid'
        },
        provider: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        details: {
            type: 'array',
            items: {
                type: 'object',
                additionalProperties: {}
            },
            writeOnly: true,
            description: 'List of account details with \'product\' (ULID) and \'quantity\' fields'
        }
    }
} as const;

export const PatchedSaleRequestWritableSchema = {
    type: 'object',
    description: 'Main serializer for creating and viewing sales.\nSupports nested creation of sale details.',
    properties: {
        branch: {
            type: 'string',
            format: 'uuid'
        },
        customer: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        details: {
            type: 'array',
            items: {
                type: 'object',
                additionalProperties: {}
            },
            writeOnly: true,
            description: 'List of sale details with \'product\' (ULID) and \'quantity\' fields'
        }
    }
} as const;

export const ProductMasterWritableSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            maxLength: 200
        },
        description: {
            type: 'string',
            nullable: true
        },
        cost_price_usd: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$'
        },
        profit_margin: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,3}(?:\\.\\d{0,2})?$'
        },
        IVA: {
            type: 'boolean'
        },
        category: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        measurement_unit: {
            type: 'string',
            format: 'uuid',
            nullable: true
        }
    },
    required: [
        'cost_price_usd',
        'name',
        'profit_margin'
    ]
} as const;

export const ProductStockSaleWritableSchema = {
    type: 'object',
    properties: {
        stock: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,6}(?:\\.\\d{0,4})?$'
        }
    },
    required: [
        'stock'
    ]
} as const;

export const ProviderWritableSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            maxLength: 200
        },
        phone: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 200
        },
        document: {
            type: 'string',
            nullable: true,
            maxLength: 40
        },
        changed_by: {
            type: 'integer',
            nullable: true
        }
    },
    required: [
        'name'
    ]
} as const;

export const RegisterUserRequestWritableSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email',
            minLength: 1,
            maxLength: 254
        },
        password: {
            type: 'string',
            writeOnly: true,
            minLength: 1,
            maxLength: 128
        },
        company_id: {
            type: 'string',
            format: 'uuid',
            writeOnly: true
        },
        branch_ids: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid',
                writeOnly: true
            },
            writeOnly: true
        },
        first_name: {
            type: 'string',
            maxLength: 150
        },
        last_name: {
            type: 'string',
            maxLength: 150
        },
        username: {
            type: 'string',
            minLength: 1,
            description: 'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
            pattern: '^[\\w.@+-]+$',
            maxLength: 150
        }
    },
    required: [
        'company_id',
        'email',
        'password',
        'username'
    ]
} as const;

export const SaleWritableSchema = {
    type: 'object',
    description: 'Main serializer for creating and viewing sales.\nSupports nested creation of sale details.',
    properties: {
        branch: {
            type: 'string',
            format: 'uuid'
        },
        customer: {
            type: 'string',
            format: 'uuid',
            nullable: true
        }
    },
    required: [
        'branch'
    ]
} as const;

export const SaleDetailWritableSchema = {
    type: 'object',
    description: 'Serializer for SaleDetail - used for reading sale details.\nFor writing, use the nested \'details\' field in SaleSerializer.',
    properties: {
        product: {
            type: 'string',
            format: 'uuid'
        },
        quantity: {
            type: 'number',
            format: 'double'
        }
    },
    required: [
        'product',
        'quantity'
    ]
} as const;

export const SalePaymentWritableSchema = {
    type: 'object',
    description: 'Serializer for creating and viewing sale payments.\nHandles currency conversion and payment status updates.',
    properties: {
        currency: {
            type: 'string',
            maxLength: 3
        },
        payment_method: {
            type: 'string'
        },
        discount: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$'
        }
    },
    required: [
        'currency',
        'discount',
        'payment_method'
    ]
} as const;

export const SalePaymentRequestWritableSchema = {
    type: 'object',
    description: 'Serializer for creating and viewing sale payments.\nHandles currency conversion and payment status updates.',
    properties: {
        currency: {
            type: 'string',
            minLength: 1,
            maxLength: 3
        },
        payment_method: {
            type: 'string',
            minLength: 1
        },
        discount: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$'
        },
        amount: {
            type: 'string',
            format: 'decimal',
            pattern: '^-?\\d{0,8}(?:\\.\\d{0,2})?$',
            writeOnly: true,
            description: 'Payment amount in the specified currency'
        }
    },
    required: [
        'amount',
        'currency',
        'discount',
        'payment_method'
    ]
} as const;

export const SaleRequestWritableSchema = {
    type: 'object',
    description: 'Main serializer for creating and viewing sales.\nSupports nested creation of sale details.',
    properties: {
        branch: {
            type: 'string',
            format: 'uuid'
        },
        customer: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        details: {
            type: 'array',
            items: {
                type: 'object',
                additionalProperties: {}
            },
            writeOnly: true,
            description: 'List of sale details with \'product\' (ULID) and \'quantity\' fields'
        }
    },
    required: [
        'branch',
        'details'
    ]
} as const;
