// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Main serializer for creating and viewing accounts (purchases).
 * Supports nested creation of account details.
 * Increases stock when account is created.
 */
export type Account = {
    readonly id: string;
    branch: string;
    readonly branch_name: string;
    provider?: string | null;
    readonly provider_name: string;
    readonly total_amount_usd: string;
    payment_status: PaymentStatus0CfEnum;
    readonly seq_number: number;
    readonly account_details: Array<AccountDetail>;
    readonly total_paid: string;
    readonly created_at: string;
    readonly updated_at: string;
};

/**
 * Serializer for AccountDetail - used for reading account details.
 * For writing, use the nested 'details' field in AccountSerializer.
 */
export type AccountDetail = {
    readonly id: string;
    product: string;
    readonly product_name: string;
    quantity: string;
    readonly unit_price: string;
};

/**
 * Serializer for AccountDetail - used for reading account details.
 * For writing, use the nested 'details' field in AccountSerializer.
 */
export type AccountDetailRequest = {
    product: string;
    quantity: string;
};

/**
 * Lightweight serializer for listing accounts.
 * Includes computed fields for display purposes.
 */
export type AccountList = {
    readonly id: string;
    readonly seq_number: number;
    readonly created_at: string;
    readonly updated_at: string;
    readonly total_amount_usd: string;
    payment_status: PaymentStatus0CfEnum;
    readonly branch: string;
    readonly branch_name: string;
    readonly provider: string | null;
    readonly provider_name: string;
    readonly total_paid: string;
};

/**
 * Serializer for creating and viewing account payments.
 * Handles currency conversion and payment status updates.
 */
export type AccountPayment = {
    readonly id: string;
    currency: string;
    payment_method: string;
    readonly payment_date: string;
    REF?: string | null;
    readonly total_amount_usd: string;
    readonly total_amount_ves: string;
    readonly exchange_rate: string | null;
    readonly created_at: string;
};

/**
 * Serializer for creating and viewing account payments.
 * Handles currency conversion and payment status updates.
 */
export type AccountPaymentRequest = {
    currency: string;
    payment_method: string;
    REF?: string | null;
};

/**
 * Main serializer for creating and viewing accounts (purchases).
 * Supports nested creation of account details.
 * Increases stock when account is created.
 */
export type AccountRequest = {
    branch: string;
    provider?: string | null;
};

export type Branch = {
    name: string;
    address?: string | null;
    phone?: string | null;
    email?: string | null;
    readonly id: string;
};

export type BranchRequest = {
    name: string;
    address?: string | null;
    phone?: string | null;
    email?: string | null;
};

export type Category = {
    name: string;
    readonly id: string;
};

export type CategoryRequest = {
    name: string;
};

export type Company = {
    name: string;
    email: string;
    max_branches: number;
    license_date: string;
    readonly id: string;
};

export type CompanyRequest = {
    name: string;
    email: string;
    max_branches: number;
    license_date: string;
};

export type CustomUser = {
    email: string;
    first_name?: string;
    last_name?: string;
    company_id: string;
    branch_ids?: Array<string>;
};

export type CustomUserRequest = {
    email: string;
    first_name?: string;
    last_name?: string;
    company_id: string;
    branch_ids?: Array<string>;
};

export type Customer = {
    readonly id: string;
    company: Company;
    readonly created_at: string;
    name: string;
    phone?: string | null;
    email?: string | null;
    document?: string | null;
    changed_by?: number | null;
};

export type CustomerRequest = {
    name: string;
    phone?: string | null;
    email?: string | null;
    document?: string | null;
    changed_by?: number | null;
};

export type MeasurementUnit = {
    name: string;
    decimals?: boolean;
    readonly id: string;
};

export type MeasurementUnitRequest = {
    name: string;
    decimals?: boolean;
};

export type PaginatedAccountListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AccountList>;
};

export type PaginatedSaleListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<SaleList>;
};

/**
 * Main serializer for creating and viewing accounts (purchases).
 * Supports nested creation of account details.
 * Increases stock when account is created.
 */
export type PatchedAccountRequest = {
    branch?: string;
    provider?: string | null;
};

export type PatchedBranchRequest = {
    name?: string;
    address?: string | null;
    phone?: string | null;
    email?: string | null;
};

export type PatchedCategoryRequest = {
    name?: string;
};

export type PatchedCompanyRequest = {
    name?: string;
    email?: string;
    max_branches?: number;
    license_date?: string;
};

export type PatchedCustomUserRequest = {
    email?: string;
    first_name?: string;
    last_name?: string;
    company_id?: string;
    branch_ids?: Array<string>;
};

export type PatchedCustomerRequest = {
    name?: string;
    phone?: string | null;
    email?: string | null;
    document?: string | null;
    changed_by?: number | null;
};

export type PatchedMeasurementUnitRequest = {
    name?: string;
    decimals?: boolean;
};

/**
 * Serializador completo para Creación, Edición y Detalle
 */
export type PatchedProductWriteDetailRequest = {
    name?: string;
    description?: string | null;
    cost_price_usd?: string;
    profit_margin?: string;
    IVA?: boolean;
    category?: string | null;
    measurement_unit?: string | null;
    selling_units?: Array<ProductSellingUnitRequest>;
};

export type PatchedProviderRequest = {
    name?: string;
    phone?: string | null;
    email?: string | null;
    document?: string | null;
    changed_by?: number | null;
};

/**
 * Main serializer for creating and viewing sales.
 * Supports nested creation of sale details.
 */
export type PatchedSaleRequest = {
    branch?: string;
    customer?: string | null;
};

/**
 * * `PENDING` - Pending
 * * `PARTIALLY_PAID` - Partially Paid
 * * `PAID` - Paid
 */
export type PaymentStatus0CfEnum = 'PENDING' | 'PARTIALLY_PAID' | 'PAID';

/**
 * * `PENDING` - Pending
 * * `PARTIALLY_PAID` - Partially Paid
 * * `PAID` - Paid
 * * `OVERPAID` - Overpaid
 */
export type PaymentStatusC54Enum = 'PENDING' | 'PARTIALLY_PAID' | 'PAID' | 'OVERPAID';

/**
 * Serializador ligero para listados generales
 */
export type ProductMaster = {
    readonly id: string;
    name: string;
    description?: string | null;
    cost_price_usd: string;
    profit_margin: string;
    IVA?: boolean;
    category?: string | null;
    measurement_unit?: string | null;
};

export type ProductSellingUnit = {
    id?: string;
    name: string;
    unit_conversion_factor: string;
    measurement_unit: string;
};

export type ProductSellingUnitRequest = {
    id?: string;
    name: string;
    unit_conversion_factor: string;
    measurement_unit: string;
};

export type ProductStockSale = {
    readonly product_id: string;
    stock: string;
};

/**
 * Serializador completo para Creación, Edición y Detalle
 */
export type ProductWriteDetail = {
    readonly id: string;
    name: string;
    description?: string | null;
    cost_price_usd: string;
    profit_margin: string;
    IVA?: boolean;
    category?: string | null;
    measurement_unit?: string | null;
    selling_units?: Array<ProductSellingUnit>;
};

/**
 * Serializador completo para Creación, Edición y Detalle
 */
export type ProductWriteDetailRequest = {
    name: string;
    description?: string | null;
    cost_price_usd: string;
    profit_margin: string;
    IVA?: boolean;
    category?: string | null;
    measurement_unit?: string | null;
    selling_units?: Array<ProductSellingUnitRequest>;
};

export type Provider = {
    readonly id: string;
    company: Company;
    readonly created_at: string;
    name: string;
    phone?: string | null;
    email?: string | null;
    document?: string | null;
    changed_by?: number | null;
};

export type ProviderRequest = {
    name: string;
    phone?: string | null;
    email?: string | null;
    document?: string | null;
    changed_by?: number | null;
};

export type RegisterUser = {
    email: string;
    first_name?: string;
    last_name?: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
};

export type RegisterUserRequest = {
    email: string;
    first_name?: string;
    last_name?: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
};

/**
 * Main serializer for creating and viewing sales.
 * Supports nested creation of sale details.
 */
export type Sale = {
    readonly id: string;
    branch: string;
    readonly branch_name: string;
    customer?: string | null;
    readonly customer_name: string;
    readonly total_amount_usd: string;
    payment_status: PaymentStatusC54Enum;
    readonly seq_number: number;
    readonly sale_details: Array<SaleDetail>;
    readonly total_paid: string;
    readonly created_at: string;
    readonly updated_at: string;
};

/**
 * Serializer for SaleDetail - used for reading sale details.
 * For writing, use the nested 'details' field in SaleSerializer.
 */
export type SaleDetail = {
    readonly id: string;
    product: string;
    readonly product_name: string;
    quantity: string;
    readonly unit_price: string;
};

/**
 * Serializer for SaleDetail - used for reading sale details.
 * For writing, use the nested 'details' field in SaleSerializer.
 */
export type SaleDetailRequest = {
    product: string;
    quantity: string;
};

/**
 * Lightweight serializer for listing sales.
 * Includes computed fields for display purposes.
 */
export type SaleList = {
    readonly id: string;
    readonly seq_number: number;
    readonly created_at: string;
    readonly updated_at: string;
    readonly total_amount_usd: string;
    payment_status: PaymentStatusC54Enum;
    readonly branch: string;
    readonly branch_name: string;
    readonly customer: string | null;
    readonly customer_name: string;
    readonly total_paid: string;
};

/**
 * Serializer for creating and viewing sale payments.
 * Handles currency conversion and payment status updates.
 */
export type SalePayment = {
    readonly id: string;
    currency: string;
    payment_method: string;
    readonly payment_date: string;
    discount?: string;
    readonly total_amount_usd: string;
    readonly total_amount_ves: string;
    readonly exchange_rate: string | null;
    readonly created_at: string;
};

/**
 * Serializer for creating and viewing sale payments.
 * Handles currency conversion and payment status updates.
 */
export type SalePaymentRequest = {
    currency: string;
    payment_method: string;
    discount?: string;
};

/**
 * Main serializer for creating and viewing sales.
 * Supports nested creation of sale details.
 */
export type SaleRequest = {
    branch: string;
    customer?: string | null;
};

export type TokenRefresh = {
    readonly access: string;
};

export type TokenRefreshRequest = {
    refresh: string;
};

/**
 * Main serializer for creating and viewing accounts (purchases).
 * Supports nested creation of account details.
 * Increases stock when account is created.
 */
export type AccountWritable = {
    branch: string;
    provider?: string | null;
};

/**
 * Serializer for AccountDetail - used for reading account details.
 * For writing, use the nested 'details' field in AccountSerializer.
 */
export type AccountDetailWritable = {
    product: string;
    quantity: string;
};

/**
 * Serializer for creating and viewing account payments.
 * Handles currency conversion and payment status updates.
 */
export type AccountPaymentWritable = {
    currency: string;
    payment_method: string;
    REF?: string | null;
};

/**
 * Serializer for creating and viewing account payments.
 * Handles currency conversion and payment status updates.
 */
export type AccountPaymentRequestWritable = {
    currency: string;
    payment_method: string;
    REF?: string | null;
    /**
     * Payment amount in the specified currency
     */
    amount: string;
};

/**
 * Main serializer for creating and viewing accounts (purchases).
 * Supports nested creation of account details.
 * Increases stock when account is created.
 */
export type AccountRequestWritable = {
    branch: string;
    provider?: string | null;
    /**
     * List of account details with 'product' (ULID) and 'quantity' fields
     */
    details: Array<{
        [key: string]: unknown;
    }>;
};

export type BranchWritable = {
    name: string;
    address?: string | null;
    phone?: string | null;
    email?: string | null;
};

export type CategoryWritable = {
    name: string;
};

export type CompanyWritable = {
    name: string;
    email: string;
    max_branches: number;
    license_date: string;
};

export type CustomerWritable = {
    name: string;
    phone?: string | null;
    email?: string | null;
    document?: string | null;
    changed_by?: number | null;
};

export type MeasurementUnitWritable = {
    name: string;
    decimals?: boolean;
};

export type PaginatedAccountListListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<unknown>;
};

export type PaginatedSaleListListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<unknown>;
};

/**
 * Main serializer for creating and viewing accounts (purchases).
 * Supports nested creation of account details.
 * Increases stock when account is created.
 */
export type PatchedAccountRequestWritable = {
    branch?: string;
    provider?: string | null;
    /**
     * List of account details with 'product' (ULID) and 'quantity' fields
     */
    details?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * Main serializer for creating and viewing sales.
 * Supports nested creation of sale details.
 */
export type PatchedSaleRequestWritable = {
    branch?: string;
    customer?: string | null;
    /**
     * List of sale details with 'product' (ULID) and 'quantity' fields
     */
    details?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * Serializador ligero para listados generales
 */
export type ProductMasterWritable = {
    name: string;
    description?: string | null;
    cost_price_usd: string;
    profit_margin: string;
    IVA?: boolean;
    category?: string | null;
    measurement_unit?: string | null;
};

export type ProductStockSaleWritable = {
    stock: string;
};

/**
 * Serializador completo para Creación, Edición y Detalle
 */
export type ProductWriteDetailWritable = {
    name: string;
    description?: string | null;
    cost_price_usd: string;
    profit_margin: string;
    IVA?: boolean;
    category?: string | null;
    measurement_unit?: string | null;
    selling_units?: Array<ProductSellingUnit>;
};

export type ProviderWritable = {
    name: string;
    phone?: string | null;
    email?: string | null;
    document?: string | null;
    changed_by?: number | null;
};

export type RegisterUserRequestWritable = {
    email: string;
    password: string;
    company_id: string;
    branch_ids?: Array<string>;
    first_name?: string;
    last_name?: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
};

/**
 * Main serializer for creating and viewing sales.
 * Supports nested creation of sale details.
 */
export type SaleWritable = {
    branch: string;
    customer?: string | null;
};

/**
 * Serializer for SaleDetail - used for reading sale details.
 * For writing, use the nested 'details' field in SaleSerializer.
 */
export type SaleDetailWritable = {
    product: string;
    quantity: string;
};

/**
 * Serializer for creating and viewing sale payments.
 * Handles currency conversion and payment status updates.
 */
export type SalePaymentWritable = {
    currency: string;
    payment_method: string;
    discount?: string;
};

/**
 * Serializer for creating and viewing sale payments.
 * Handles currency conversion and payment status updates.
 */
export type SalePaymentRequestWritable = {
    currency: string;
    payment_method: string;
    discount?: string;
    /**
     * Payment amount in the specified currency
     */
    amount: string;
};

/**
 * Main serializer for creating and viewing sales.
 * Supports nested creation of sale details.
 */
export type SaleRequestWritable = {
    branch: string;
    customer?: string | null;
    /**
     * List of sale details with 'product' (ULID) and 'quantity' fields
     */
    details: Array<{
        [key: string]: unknown;
    }>;
};

export type V1AccountsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/v1/accounts/';
};

export type V1AccountsListResponses = {
    200: PaginatedAccountListList;
};

export type V1AccountsListResponse = V1AccountsListResponses[keyof V1AccountsListResponses];

export type V1AccountsCreateData = {
    body: AccountRequestWritable;
    path?: never;
    query?: never;
    url: '/v1/accounts/';
};

export type V1AccountsCreateResponses = {
    201: Account;
};

export type V1AccountsCreateResponse = V1AccountsCreateResponses[keyof V1AccountsCreateResponses];

export type V1AccountsPaymentsListData = {
    body?: never;
    path: {
        account_id: string;
    };
    query?: never;
    url: '/v1/accounts/{account_id}/payments/';
};

export type V1AccountsPaymentsListResponses = {
    200: Array<AccountPayment>;
};

export type V1AccountsPaymentsListResponse = V1AccountsPaymentsListResponses[keyof V1AccountsPaymentsListResponses];

export type V1AccountsPaymentsCreateData = {
    body: AccountPaymentRequestWritable;
    path: {
        account_id: string;
    };
    query?: never;
    url: '/v1/accounts/{account_id}/payments/';
};

export type V1AccountsPaymentsCreateResponses = {
    201: AccountPayment;
};

export type V1AccountsPaymentsCreateResponse = V1AccountsPaymentsCreateResponses[keyof V1AccountsPaymentsCreateResponses];

export type V1AccountsDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/accounts/{id}/';
};

export type V1AccountsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type V1AccountsDestroyResponse = V1AccountsDestroyResponses[keyof V1AccountsDestroyResponses];

export type V1AccountsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/accounts/{id}/';
};

export type V1AccountsRetrieveResponses = {
    200: Account;
};

export type V1AccountsRetrieveResponse = V1AccountsRetrieveResponses[keyof V1AccountsRetrieveResponses];

export type V1AccountsPartialUpdateData = {
    body?: PatchedAccountRequestWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/accounts/{id}/';
};

export type V1AccountsPartialUpdateResponses = {
    200: Account;
};

export type V1AccountsPartialUpdateResponse = V1AccountsPartialUpdateResponses[keyof V1AccountsPartialUpdateResponses];

export type V1AccountsUpdateData = {
    body: AccountRequestWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/accounts/{id}/';
};

export type V1AccountsUpdateResponses = {
    200: Account;
};

export type V1AccountsUpdateResponse = V1AccountsUpdateResponses[keyof V1AccountsUpdateResponses];

export type V1BranchListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/branch/';
};

export type V1BranchListResponses = {
    200: Array<Branch>;
};

export type V1BranchListResponse = V1BranchListResponses[keyof V1BranchListResponses];

export type V1BranchCreateData = {
    body: BranchRequest;
    path?: never;
    query?: never;
    url: '/v1/branch/';
};

export type V1BranchCreateResponses = {
    201: Branch;
};

export type V1BranchCreateResponse = V1BranchCreateResponses[keyof V1BranchCreateResponses];

export type V1BranchDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/branch/{id}/';
};

export type V1BranchDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type V1BranchDestroyResponse = V1BranchDestroyResponses[keyof V1BranchDestroyResponses];

export type V1BranchRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/branch/{id}/';
};

export type V1BranchRetrieveResponses = {
    200: Branch;
};

export type V1BranchRetrieveResponse = V1BranchRetrieveResponses[keyof V1BranchRetrieveResponses];

export type V1BranchPartialUpdateData = {
    body?: PatchedBranchRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/branch/{id}/';
};

export type V1BranchPartialUpdateResponses = {
    200: Branch;
};

export type V1BranchPartialUpdateResponse = V1BranchPartialUpdateResponses[keyof V1BranchPartialUpdateResponses];

export type V1BranchUpdateData = {
    body: BranchRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/branch/{id}/';
};

export type V1BranchUpdateResponses = {
    200: Branch;
};

export type V1BranchUpdateResponse = V1BranchUpdateResponses[keyof V1BranchUpdateResponses];

export type V1CategoryListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/category/';
};

export type V1CategoryListResponses = {
    200: Array<Category>;
};

export type V1CategoryListResponse = V1CategoryListResponses[keyof V1CategoryListResponses];

export type V1CategoryCreateData = {
    body: CategoryRequest;
    path?: never;
    query?: never;
    url: '/v1/category/';
};

export type V1CategoryCreateResponses = {
    201: Category;
};

export type V1CategoryCreateResponse = V1CategoryCreateResponses[keyof V1CategoryCreateResponses];

export type V1CategoryDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/category/{id}/';
};

export type V1CategoryDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type V1CategoryDestroyResponse = V1CategoryDestroyResponses[keyof V1CategoryDestroyResponses];

export type V1CategoryRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/category/{id}/';
};

export type V1CategoryRetrieveResponses = {
    200: Category;
};

export type V1CategoryRetrieveResponse = V1CategoryRetrieveResponses[keyof V1CategoryRetrieveResponses];

export type V1CategoryPartialUpdateData = {
    body?: PatchedCategoryRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/category/{id}/';
};

export type V1CategoryPartialUpdateResponses = {
    200: Category;
};

export type V1CategoryPartialUpdateResponse = V1CategoryPartialUpdateResponses[keyof V1CategoryPartialUpdateResponses];

export type V1CategoryUpdateData = {
    body: CategoryRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/category/{id}/';
};

export type V1CategoryUpdateResponses = {
    200: Category;
};

export type V1CategoryUpdateResponse = V1CategoryUpdateResponses[keyof V1CategoryUpdateResponses];

export type V1CompanyRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/company/';
};

export type V1CompanyRetrieveResponses = {
    200: Company;
};

export type V1CompanyRetrieveResponse = V1CompanyRetrieveResponses[keyof V1CompanyRetrieveResponses];

export type V1CompanyPartialUpdateData = {
    body?: PatchedCompanyRequest;
    path?: never;
    query?: never;
    url: '/v1/company/';
};

export type V1CompanyPartialUpdateResponses = {
    200: Company;
};

export type V1CompanyPartialUpdateResponse = V1CompanyPartialUpdateResponses[keyof V1CompanyPartialUpdateResponses];

export type V1CompanyCreateData = {
    body: CompanyRequest;
    path?: never;
    query?: never;
    url: '/v1/company/';
};

export type V1CompanyCreateResponses = {
    201: Company;
};

export type V1CompanyCreateResponse = V1CompanyCreateResponses[keyof V1CompanyCreateResponses];

export type V1CompanyUpdateData = {
    body: CompanyRequest;
    path?: never;
    query?: never;
    url: '/v1/company/';
};

export type V1CompanyUpdateResponses = {
    200: Company;
};

export type V1CompanyUpdateResponse = V1CompanyUpdateResponses[keyof V1CompanyUpdateResponses];

export type V1CustomersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/customers/';
};

export type V1CustomersListResponses = {
    200: Array<Customer>;
};

export type V1CustomersListResponse = V1CustomersListResponses[keyof V1CustomersListResponses];

export type V1CustomersCreateData = {
    body: CustomerRequest;
    path?: never;
    query?: never;
    url: '/v1/customers/';
};

export type V1CustomersCreateResponses = {
    201: Customer;
};

export type V1CustomersCreateResponse = V1CustomersCreateResponses[keyof V1CustomersCreateResponses];

export type V1CustomersDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/customers/{id}/';
};

export type V1CustomersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type V1CustomersDestroyResponse = V1CustomersDestroyResponses[keyof V1CustomersDestroyResponses];

export type V1CustomersRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/customers/{id}/';
};

export type V1CustomersRetrieveResponses = {
    200: Customer;
};

export type V1CustomersRetrieveResponse = V1CustomersRetrieveResponses[keyof V1CustomersRetrieveResponses];

export type V1CustomersPartialUpdateData = {
    body?: PatchedCustomerRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/customers/{id}/';
};

export type V1CustomersPartialUpdateResponses = {
    200: Customer;
};

export type V1CustomersPartialUpdateResponse = V1CustomersPartialUpdateResponses[keyof V1CustomersPartialUpdateResponses];

export type V1CustomersUpdateData = {
    body: CustomerRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/customers/{id}/';
};

export type V1CustomersUpdateResponses = {
    200: Customer;
};

export type V1CustomersUpdateResponse = V1CustomersUpdateResponses[keyof V1CustomersUpdateResponses];

export type V1ExchangeRatesRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/exchange-rates/{id}/';
};

export type V1ExchangeRatesRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type V1ExchangeRatesHistoryRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/exchange-rates/history/';
};

export type V1ExchangeRatesHistoryRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type V1ExchangeRatesTodayRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/exchange-rates/today/';
};

export type V1ExchangeRatesTodayRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type V1LoginCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/login/';
};

export type V1LoginCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type V1LogoutCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/logout/';
};

export type V1LogoutCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type V1MeasurementListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/measurement/';
};

export type V1MeasurementListResponses = {
    200: Array<MeasurementUnit>;
};

export type V1MeasurementListResponse = V1MeasurementListResponses[keyof V1MeasurementListResponses];

export type V1MeasurementCreateData = {
    body: MeasurementUnitRequest;
    path?: never;
    query?: never;
    url: '/v1/measurement/';
};

export type V1MeasurementCreateResponses = {
    201: MeasurementUnit;
};

export type V1MeasurementCreateResponse = V1MeasurementCreateResponses[keyof V1MeasurementCreateResponses];

export type V1MeasurementDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/measurement/{id}/';
};

export type V1MeasurementDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type V1MeasurementDestroyResponse = V1MeasurementDestroyResponses[keyof V1MeasurementDestroyResponses];

export type V1MeasurementRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/measurement/{id}/';
};

export type V1MeasurementRetrieveResponses = {
    200: MeasurementUnit;
};

export type V1MeasurementRetrieveResponse = V1MeasurementRetrieveResponses[keyof V1MeasurementRetrieveResponses];

export type V1MeasurementPartialUpdateData = {
    body?: PatchedMeasurementUnitRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/measurement/{id}/';
};

export type V1MeasurementPartialUpdateResponses = {
    200: MeasurementUnit;
};

export type V1MeasurementPartialUpdateResponse = V1MeasurementPartialUpdateResponses[keyof V1MeasurementPartialUpdateResponses];

export type V1MeasurementUpdateData = {
    body: MeasurementUnitRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/measurement/{id}/';
};

export type V1MeasurementUpdateResponses = {
    200: MeasurementUnit;
};

export type V1MeasurementUpdateResponse = V1MeasurementUpdateResponses[keyof V1MeasurementUpdateResponses];

export type V1ProductListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/product/';
};

export type V1ProductListResponses = {
    200: Array<ProductMaster>;
};

export type V1ProductListResponse = V1ProductListResponses[keyof V1ProductListResponses];

export type V1ProductCreateData = {
    body: ProductWriteDetailRequest;
    path?: never;
    query?: never;
    url: '/v1/product/';
};

export type V1ProductCreateResponses = {
    201: ProductWriteDetail;
};

export type V1ProductCreateResponse = V1ProductCreateResponses[keyof V1ProductCreateResponses];

export type V1ProductBranchStockListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/product-branch-stock/';
};

export type V1ProductBranchStockListResponses = {
    200: Array<ProductStockSale>;
};

export type V1ProductBranchStockListResponse = V1ProductBranchStockListResponses[keyof V1ProductBranchStockListResponses];

export type V1ProductDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/product/{id}/';
};

export type V1ProductDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type V1ProductDestroyResponse = V1ProductDestroyResponses[keyof V1ProductDestroyResponses];

export type V1ProductRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/product/{id}/';
};

export type V1ProductRetrieveResponses = {
    200: ProductWriteDetail;
};

export type V1ProductRetrieveResponse = V1ProductRetrieveResponses[keyof V1ProductRetrieveResponses];

export type V1ProductPartialUpdateData = {
    body?: PatchedProductWriteDetailRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/product/{id}/';
};

export type V1ProductPartialUpdateResponses = {
    200: ProductWriteDetail;
};

export type V1ProductPartialUpdateResponse = V1ProductPartialUpdateResponses[keyof V1ProductPartialUpdateResponses];

export type V1ProductUpdateData = {
    body: ProductWriteDetailRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/product/{id}/';
};

export type V1ProductUpdateResponses = {
    200: ProductWriteDetail;
};

export type V1ProductUpdateResponse = V1ProductUpdateResponses[keyof V1ProductUpdateResponses];

export type V1ProvidersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/providers/';
};

export type V1ProvidersListResponses = {
    200: Array<Provider>;
};

export type V1ProvidersListResponse = V1ProvidersListResponses[keyof V1ProvidersListResponses];

export type V1ProvidersCreateData = {
    body: ProviderRequest;
    path?: never;
    query?: never;
    url: '/v1/providers/';
};

export type V1ProvidersCreateResponses = {
    201: Provider;
};

export type V1ProvidersCreateResponse = V1ProvidersCreateResponses[keyof V1ProvidersCreateResponses];

export type V1ProvidersDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/providers/{id}/';
};

export type V1ProvidersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type V1ProvidersDestroyResponse = V1ProvidersDestroyResponses[keyof V1ProvidersDestroyResponses];

export type V1ProvidersRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/providers/{id}/';
};

export type V1ProvidersRetrieveResponses = {
    200: Provider;
};

export type V1ProvidersRetrieveResponse = V1ProvidersRetrieveResponses[keyof V1ProvidersRetrieveResponses];

export type V1ProvidersPartialUpdateData = {
    body?: PatchedProviderRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/providers/{id}/';
};

export type V1ProvidersPartialUpdateResponses = {
    200: Provider;
};

export type V1ProvidersPartialUpdateResponse = V1ProvidersPartialUpdateResponses[keyof V1ProvidersPartialUpdateResponses];

export type V1ProvidersUpdateData = {
    body: ProviderRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/providers/{id}/';
};

export type V1ProvidersUpdateResponses = {
    200: Provider;
};

export type V1ProvidersUpdateResponse = V1ProvidersUpdateResponses[keyof V1ProvidersUpdateResponses];

export type V1RefreshCreateData = {
    body: TokenRefreshRequest;
    path?: never;
    query?: never;
    url: '/v1/refresh/';
};

export type V1RefreshCreateResponses = {
    200: TokenRefresh;
};

export type V1RefreshCreateResponse = V1RefreshCreateResponses[keyof V1RefreshCreateResponses];

export type V1RegisterCreateData = {
    body: RegisterUserRequestWritable;
    path?: never;
    query?: never;
    url: '/v1/register/';
};

export type V1RegisterCreateResponses = {
    201: RegisterUser;
};

export type V1RegisterCreateResponse = V1RegisterCreateResponses[keyof V1RegisterCreateResponses];

export type V1SalesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/v1/sales/';
};

export type V1SalesListResponses = {
    200: PaginatedSaleListList;
};

export type V1SalesListResponse = V1SalesListResponses[keyof V1SalesListResponses];

export type V1SalesCreateData = {
    body: SaleRequestWritable;
    path?: never;
    query?: never;
    url: '/v1/sales/';
};

export type V1SalesCreateResponses = {
    201: Sale;
};

export type V1SalesCreateResponse = V1SalesCreateResponses[keyof V1SalesCreateResponses];

export type V1SalesDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/sales/{id}/';
};

export type V1SalesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type V1SalesDestroyResponse = V1SalesDestroyResponses[keyof V1SalesDestroyResponses];

export type V1SalesRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/sales/{id}/';
};

export type V1SalesRetrieveResponses = {
    200: Sale;
};

export type V1SalesRetrieveResponse = V1SalesRetrieveResponses[keyof V1SalesRetrieveResponses];

export type V1SalesPartialUpdateData = {
    body?: PatchedSaleRequestWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/sales/{id}/';
};

export type V1SalesPartialUpdateResponses = {
    200: Sale;
};

export type V1SalesPartialUpdateResponse = V1SalesPartialUpdateResponses[keyof V1SalesPartialUpdateResponses];

export type V1SalesUpdateData = {
    body: SaleRequestWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/sales/{id}/';
};

export type V1SalesUpdateResponses = {
    200: Sale;
};

export type V1SalesUpdateResponse = V1SalesUpdateResponses[keyof V1SalesUpdateResponses];

export type V1SalesPaymentsListData = {
    body?: never;
    path: {
        sale_id: string;
    };
    query?: never;
    url: '/v1/sales/{sale_id}/payments/';
};

export type V1SalesPaymentsListResponses = {
    200: Array<SalePayment>;
};

export type V1SalesPaymentsListResponse = V1SalesPaymentsListResponses[keyof V1SalesPaymentsListResponses];

export type V1SalesPaymentsCreateData = {
    body: SalePaymentRequestWritable;
    path: {
        sale_id: string;
    };
    query?: never;
    url: '/v1/sales/{sale_id}/payments/';
};

export type V1SalesPaymentsCreateResponses = {
    201: SalePayment;
};

export type V1SalesPaymentsCreateResponse = V1SalesPaymentsCreateResponses[keyof V1SalesPaymentsCreateResponses];

export type V1UserBranchesRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/user-branches/';
};

export type V1UserBranchesRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type V1UserBranchesUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/user-branches/';
};

export type V1UserBranchesUpdateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type V1UserInfoRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/user-info/';
};

export type V1UserInfoRetrieveResponses = {
    200: CustomUser;
};

export type V1UserInfoRetrieveResponse = V1UserInfoRetrieveResponses[keyof V1UserInfoRetrieveResponses];

export type V1UserInfoPartialUpdateData = {
    body?: PatchedCustomUserRequest;
    path?: never;
    query?: never;
    url: '/v1/user-info/';
};

export type V1UserInfoPartialUpdateResponses = {
    200: CustomUser;
};

export type V1UserInfoPartialUpdateResponse = V1UserInfoPartialUpdateResponses[keyof V1UserInfoPartialUpdateResponses];

export type V1UserInfoUpdateData = {
    body: CustomUserRequest;
    path?: never;
    query?: never;
    url: '/v1/user-info/';
};

export type V1UserInfoUpdateResponses = {
    200: CustomUser;
};

export type V1UserInfoUpdateResponse = V1UserInfoUpdateResponses[keyof V1UserInfoUpdateResponses];
