// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Serializer for AccountDetail - used for reading account details.
 * For writing, use the nested 'details' field in AccountSerializer.
 */
export const zAccountDetail = z.object({
    id: z.string().uuid().readonly(),
    product: z.string().uuid(),
    product_name: z.string().readonly(),
    quantity: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/),
    unit_price: z.string().regex(/^-?\d{0,10}(?:\.\d{0,2})?$/).readonly()
});

/**
 * Serializer for AccountDetail - used for reading account details.
 * For writing, use the nested 'details' field in AccountSerializer.
 */
export const zAccountDetailRequest = z.object({
    product: z.string().uuid(),
    quantity: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/)
});

/**
 * Serializer for creating and viewing account payments.
 * Handles currency conversion and payment status updates.
 */
export const zAccountPayment = z.object({
    id: z.string().uuid().readonly(),
    currency: z.string().max(3),
    payment_method: z.string(),
    payment_date: z.string().datetime().readonly(),
    REF: z.union([
        z.string().max(100),
        z.null()
    ]).optional(),
    total_amount_usd: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/).readonly(),
    total_amount_ves: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/).readonly(),
    exchange_rate: z.union([
        z.string().uuid().readonly(),
        z.null()
    ]).readonly(),
    created_at: z.string().datetime().readonly()
});

/**
 * Serializer for creating and viewing account payments.
 * Handles currency conversion and payment status updates.
 */
export const zAccountPaymentRequest = z.object({
    currency: z.string().min(1).max(3),
    payment_method: z.string().min(1),
    REF: z.union([
        z.string().max(100),
        z.null()
    ]).optional()
});

/**
 * Main serializer for creating and viewing accounts (purchases).
 * Supports nested creation of account details.
 * Increases stock when account is created.
 */
export const zAccountRequest = z.object({
    branch: z.string().uuid(),
    provider: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

export const zBranch = z.object({
    name: z.string().max(200),
    address: z.union([
        z.string().max(200),
        z.null()
    ]).optional(),
    phone: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().email().max(200),
        z.null()
    ]).optional(),
    id: z.string().uuid().readonly()
});

export const zBranchRequest = z.object({
    name: z.string().min(1).max(200),
    address: z.union([
        z.string().max(200),
        z.null()
    ]).optional(),
    phone: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().email().max(200),
        z.null()
    ]).optional()
});

export const zCategory = z.object({
    name: z.string().max(200),
    id: z.string().uuid().readonly()
});

export const zCategoryRequest = z.object({
    name: z.string().min(1).max(200)
});

export const zCompany = z.object({
    name: z.string().max(100),
    email: z.string().email().max(200),
    max_branches: z.number().int().gte(0).lte(2147483647),
    license_date: z.string().date(),
    id: z.string().uuid().readonly()
});

export const zCompanyRequest = z.object({
    name: z.string().min(1).max(100),
    email: z.string().email().min(1).max(200),
    max_branches: z.number().int().gte(0).lte(2147483647),
    license_date: z.string().date()
});

export const zCustomUser = z.object({
    email: z.string().email().max(254),
    first_name: z.string().max(150).optional(),
    last_name: z.string().max(150).optional(),
    company_id: z.string().uuid(),
    branch_ids: z.array(z.string().uuid()).optional()
});

export const zCustomUserRequest = z.object({
    email: z.string().email().min(1).max(254),
    first_name: z.string().max(150).optional(),
    last_name: z.string().max(150).optional(),
    company_id: z.string().uuid(),
    branch_ids: z.array(z.string().uuid()).optional()
});

export const zCustomer = z.object({
    id: z.string().uuid().readonly(),
    company: zCompany,
    created_at: z.string().datetime().readonly(),
    name: z.string().max(200),
    phone: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().email().max(200),
        z.null()
    ]).optional(),
    document: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    changed_by: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

export const zCustomerRequest = z.object({
    name: z.string().min(1).max(200),
    phone: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().email().max(200),
        z.null()
    ]).optional(),
    document: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    changed_by: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

export const zMeasurementUnit = z.object({
    name: z.string().max(200),
    decimals: z.boolean().optional(),
    id: z.string().uuid().readonly()
});

export const zMeasurementUnitRequest = z.object({
    name: z.string().min(1).max(200),
    decimals: z.boolean().optional()
});

/**
 * Main serializer for creating and viewing accounts (purchases).
 * Supports nested creation of account details.
 * Increases stock when account is created.
 */
export const zPatchedAccountRequest = z.object({
    branch: z.string().uuid().optional(),
    provider: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

export const zPatchedBranchRequest = z.object({
    name: z.string().min(1).max(200).optional(),
    address: z.union([
        z.string().max(200),
        z.null()
    ]).optional(),
    phone: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().email().max(200),
        z.null()
    ]).optional()
});

export const zPatchedCategoryRequest = z.object({
    name: z.string().min(1).max(200).optional()
});

export const zPatchedCompanyRequest = z.object({
    name: z.string().min(1).max(100).optional(),
    email: z.string().email().min(1).max(200).optional(),
    max_branches: z.number().int().gte(0).lte(2147483647).optional(),
    license_date: z.string().date().optional()
});

export const zPatchedCustomUserRequest = z.object({
    email: z.string().email().min(1).max(254).optional(),
    first_name: z.string().max(150).optional(),
    last_name: z.string().max(150).optional(),
    company_id: z.string().uuid().optional(),
    branch_ids: z.array(z.string().uuid()).optional()
});

export const zPatchedCustomerRequest = z.object({
    name: z.string().min(1).max(200).optional(),
    phone: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().email().max(200),
        z.null()
    ]).optional(),
    document: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    changed_by: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

export const zPatchedMeasurementUnitRequest = z.object({
    name: z.string().min(1).max(200).optional(),
    decimals: z.boolean().optional()
});

export const zPatchedProviderRequest = z.object({
    name: z.string().min(1).max(200).optional(),
    phone: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().email().max(200),
        z.null()
    ]).optional(),
    document: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    changed_by: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

/**
 * Main serializer for creating and viewing sales.
 * Supports nested creation of sale details.
 */
export const zPatchedSaleRequest = z.object({
    branch: z.string().uuid().optional(),
    customer: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

/**
 * * `PENDING` - Pending
 * * `PARTIALLY_PAID` - Partially Paid
 * * `PAID` - Paid
 */
export const zPaymentStatus0CfEnum = z.enum([
    'PENDING',
    'PARTIALLY_PAID',
    'PAID'
]);

/**
 * Main serializer for creating and viewing accounts (purchases).
 * Supports nested creation of account details.
 * Increases stock when account is created.
 */
export const zAccount = z.object({
    id: z.string().uuid().readonly(),
    branch: z.string().uuid(),
    branch_name: z.string().readonly(),
    provider: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    provider_name: z.string().readonly().default('No Provider'),
    total_amount_usd: z.string().regex(/^-?\d{0,10}(?:\.\d{0,2})?$/).readonly(),
    payment_status: zPaymentStatus0CfEnum,
    seq_number: z.number().int().readonly(),
    account_details: z.array(zAccountDetail).readonly(),
    total_paid: z.string().readonly(),
    created_at: z.string().datetime().readonly(),
    updated_at: z.string().datetime().readonly()
});

/**
 * Lightweight serializer for listing accounts.
 * Includes computed fields for display purposes.
 */
export const zAccountList = z.object({
    id: z.string().uuid().readonly(),
    seq_number: z.number().int().readonly(),
    created_at: z.string().datetime().readonly(),
    updated_at: z.string().datetime().readonly(),
    total_amount_usd: z.string().regex(/^-?\d{0,10}(?:\.\d{0,2})?$/).readonly(),
    payment_status: zPaymentStatus0CfEnum,
    branch: z.string().uuid().readonly(),
    branch_name: z.string().readonly(),
    provider: z.union([
        z.string().uuid().readonly(),
        z.null()
    ]).readonly(),
    provider_name: z.string().readonly().default('No Provider'),
    total_paid: z.string().readonly()
});

export const zPaginatedAccountListList = z.object({
    count: z.number().int(),
    next: z.union([
        z.string().url(),
        z.null()
    ]).optional(),
    previous: z.union([
        z.string().url(),
        z.null()
    ]).optional(),
    results: z.array(zAccountList)
});

/**
 * * `PENDING` - Pending
 * * `PARTIALLY_PAID` - Partially Paid
 * * `PAID` - Paid
 * * `OVERPAID` - Overpaid
 */
export const zPaymentStatusC54Enum = z.enum([
    'PENDING',
    'PARTIALLY_PAID',
    'PAID',
    'OVERPAID'
]);

/**
 * Serializador ligero para listados generales
 */
export const zProductMaster = z.object({
    id: z.string().uuid().readonly(),
    name: z.string().max(200),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    cost_price_usd: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/),
    profit_margin: z.string().regex(/^-?\d{0,3}(?:\.\d{0,2})?$/),
    IVA: z.boolean().optional(),
    category: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    measurement_unit: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

export const zProductSellingUnit = z.object({
    id: z.string().optional(),
    name: z.string().max(100),
    unit_conversion_factor: z.string().regex(/^-?\d{0,10}(?:\.\d{0,10})?$/),
    measurement_unit: z.string().uuid()
});

export const zProductSellingUnitRequest = z.object({
    id: z.string().min(1).optional(),
    name: z.string().min(1).max(100),
    unit_conversion_factor: z.string().regex(/^-?\d{0,10}(?:\.\d{0,10})?$/),
    measurement_unit: z.string().uuid()
});

/**
 * Serializador completo para Creación, Edición y Detalle
 */
export const zPatchedProductWriteDetailRequest = z.object({
    name: z.string().min(1).max(200).optional(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    cost_price_usd: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/).optional(),
    profit_margin: z.string().regex(/^-?\d{0,3}(?:\.\d{0,2})?$/).optional(),
    IVA: z.boolean().optional(),
    category: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    measurement_unit: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    selling_units: z.array(zProductSellingUnitRequest).optional()
});

export const zProductStockSale = z.object({
    product_id: z.string().readonly(),
    stock: z.string().regex(/^-?\d{0,6}(?:\.\d{0,10})?$/)
});

/**
 * Serializador completo para Creación, Edición y Detalle
 */
export const zProductWriteDetail = z.object({
    id: z.string().uuid().readonly(),
    name: z.string().max(200),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    cost_price_usd: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/),
    profit_margin: z.string().regex(/^-?\d{0,3}(?:\.\d{0,2})?$/),
    IVA: z.boolean().optional(),
    category: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    measurement_unit: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    selling_units: z.array(zProductSellingUnit).optional()
});

/**
 * Serializador completo para Creación, Edición y Detalle
 */
export const zProductWriteDetailRequest = z.object({
    name: z.string().min(1).max(200),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    cost_price_usd: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/),
    profit_margin: z.string().regex(/^-?\d{0,3}(?:\.\d{0,2})?$/),
    IVA: z.boolean().optional(),
    category: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    measurement_unit: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    selling_units: z.array(zProductSellingUnitRequest).optional()
});

export const zProvider = z.object({
    id: z.string().uuid().readonly(),
    company: zCompany,
    created_at: z.string().datetime().readonly(),
    name: z.string().max(200),
    phone: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().email().max(200),
        z.null()
    ]).optional(),
    document: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    changed_by: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

export const zProviderRequest = z.object({
    name: z.string().min(1).max(200),
    phone: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().email().max(200),
        z.null()
    ]).optional(),
    document: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    changed_by: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

export const zRegisterUser = z.object({
    email: z.string().email().max(254),
    first_name: z.string().max(150).optional(),
    last_name: z.string().max(150).optional(),
    username: z.string().max(150).regex(/^[\w.@+-]+$/)
});

export const zRegisterUserRequest = z.object({
    email: z.string().email().min(1).max(254),
    first_name: z.string().max(150).optional(),
    last_name: z.string().max(150).optional(),
    username: z.string().min(1).max(150).regex(/^[\w.@+-]+$/)
});

/**
 * Serializer for SaleDetail - used for reading sale details.
 * For writing, use the nested 'details' field in SaleSerializer.
 */
export const zSaleDetail = z.object({
    id: z.string().uuid().readonly(),
    product: z.string().uuid(),
    product_name: z.string().readonly(),
    quantity: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/),
    unit_price: z.string().regex(/^-?\d{0,10}(?:\.\d{0,2})?$/).readonly()
});

/**
 * Main serializer for creating and viewing sales.
 * Supports nested creation of sale details.
 */
export const zSale = z.object({
    id: z.string().uuid().readonly(),
    branch: z.string().uuid(),
    branch_name: z.string().readonly(),
    customer: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    customer_name: z.string().readonly().default('Walk-in Customer'),
    total_amount_usd: z.string().regex(/^-?\d{0,10}(?:\.\d{0,2})?$/).readonly(),
    payment_status: zPaymentStatusC54Enum,
    seq_number: z.number().int().readonly(),
    sale_details: z.array(zSaleDetail).readonly(),
    total_paid: z.string().readonly(),
    created_at: z.string().datetime().readonly(),
    updated_at: z.string().datetime().readonly()
});

/**
 * Serializer for SaleDetail - used for reading sale details.
 * For writing, use the nested 'details' field in SaleSerializer.
 */
export const zSaleDetailRequest = z.object({
    product: z.string().uuid(),
    quantity: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/)
});

/**
 * Lightweight serializer for listing sales.
 * Includes computed fields for display purposes.
 */
export const zSaleList = z.object({
    id: z.string().uuid().readonly(),
    seq_number: z.number().int().readonly(),
    created_at: z.string().datetime().readonly(),
    updated_at: z.string().datetime().readonly(),
    total_amount_usd: z.string().regex(/^-?\d{0,10}(?:\.\d{0,2})?$/).readonly(),
    payment_status: zPaymentStatusC54Enum,
    branch: z.string().uuid().readonly(),
    branch_name: z.string().readonly(),
    customer: z.union([
        z.string().uuid().readonly(),
        z.null()
    ]).readonly(),
    customer_name: z.string().readonly().default('Walk-in Customer'),
    total_paid: z.string().readonly()
});

export const zPaginatedSaleListList = z.object({
    count: z.number().int(),
    next: z.union([
        z.string().url(),
        z.null()
    ]).optional(),
    previous: z.union([
        z.string().url(),
        z.null()
    ]).optional(),
    results: z.array(zSaleList)
});

/**
 * Serializer for creating and viewing sale payments.
 * Handles currency conversion and payment status updates.
 */
export const zSalePayment = z.object({
    id: z.string().uuid().readonly(),
    currency: z.string().max(3),
    payment_method: z.string(),
    payment_date: z.string().datetime().readonly(),
    discount: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/).optional(),
    total_amount_usd: z.string().regex(/^-?\d{0,10}(?:\.\d{0,2})?$/).readonly(),
    total_amount_ves: z.string().regex(/^-?\d{0,10}(?:\.\d{0,2})?$/).readonly(),
    exchange_rate: z.union([
        z.string().uuid().readonly(),
        z.null()
    ]).readonly(),
    created_at: z.string().datetime().readonly()
});

/**
 * Serializer for creating and viewing sale payments.
 * Handles currency conversion and payment status updates.
 */
export const zSalePaymentRequest = z.object({
    currency: z.string().min(1).max(3),
    payment_method: z.string().min(1),
    discount: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/).optional()
});

/**
 * Main serializer for creating and viewing sales.
 * Supports nested creation of sale details.
 */
export const zSaleRequest = z.object({
    branch: z.string().uuid(),
    customer: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

export const zTokenRefresh = z.object({
    access: z.string().readonly()
});

export const zTokenRefreshRequest = z.object({
    refresh: z.string().min(1)
});

/**
 * Main serializer for creating and viewing accounts (purchases).
 * Supports nested creation of account details.
 * Increases stock when account is created.
 */
export const zAccountWritable = z.object({
    branch: z.string().uuid(),
    provider: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

/**
 * Serializer for AccountDetail - used for reading account details.
 * For writing, use the nested 'details' field in AccountSerializer.
 */
export const zAccountDetailWritable = z.object({
    product: z.string().uuid(),
    quantity: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/)
});

/**
 * Serializer for creating and viewing account payments.
 * Handles currency conversion and payment status updates.
 */
export const zAccountPaymentWritable = z.object({
    currency: z.string().max(3),
    payment_method: z.string(),
    REF: z.union([
        z.string().max(100),
        z.null()
    ]).optional()
});

/**
 * Serializer for creating and viewing account payments.
 * Handles currency conversion and payment status updates.
 */
export const zAccountPaymentRequestWritable = z.object({
    currency: z.string().min(1).max(3),
    payment_method: z.string().min(1),
    REF: z.union([
        z.string().max(100),
        z.null()
    ]).optional(),
    amount: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/)
});

/**
 * Main serializer for creating and viewing accounts (purchases).
 * Supports nested creation of account details.
 * Increases stock when account is created.
 */
export const zAccountRequestWritable = z.object({
    branch: z.string().uuid(),
    provider: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    details: z.array(z.record(z.unknown()))
});

export const zBranchWritable = z.object({
    name: z.string().max(200),
    address: z.union([
        z.string().max(200),
        z.null()
    ]).optional(),
    phone: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().email().max(200),
        z.null()
    ]).optional()
});

export const zCategoryWritable = z.object({
    name: z.string().max(200)
});

export const zCompanyWritable = z.object({
    name: z.string().max(100),
    email: z.string().email().max(200),
    max_branches: z.number().int().gte(0).lte(2147483647),
    license_date: z.string().date()
});

export const zCustomerWritable = z.object({
    name: z.string().max(200),
    phone: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().email().max(200),
        z.null()
    ]).optional(),
    document: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    changed_by: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

export const zMeasurementUnitWritable = z.object({
    name: z.string().max(200),
    decimals: z.boolean().optional()
});

export const zPaginatedAccountListListWritable = z.object({
    count: z.number().int(),
    next: z.union([
        z.string().url(),
        z.null()
    ]).optional(),
    previous: z.union([
        z.string().url(),
        z.null()
    ]).optional(),
    results: z.array(z.unknown())
});

export const zPaginatedSaleListListWritable = z.object({
    count: z.number().int(),
    next: z.union([
        z.string().url(),
        z.null()
    ]).optional(),
    previous: z.union([
        z.string().url(),
        z.null()
    ]).optional(),
    results: z.array(z.unknown())
});

/**
 * Main serializer for creating and viewing accounts (purchases).
 * Supports nested creation of account details.
 * Increases stock when account is created.
 */
export const zPatchedAccountRequestWritable = z.object({
    branch: z.string().uuid().optional(),
    provider: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    details: z.array(z.record(z.unknown())).optional()
});

/**
 * Main serializer for creating and viewing sales.
 * Supports nested creation of sale details.
 */
export const zPatchedSaleRequestWritable = z.object({
    branch: z.string().uuid().optional(),
    customer: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    details: z.array(z.record(z.unknown())).optional()
});

/**
 * Serializador ligero para listados generales
 */
export const zProductMasterWritable = z.object({
    name: z.string().max(200),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    cost_price_usd: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/),
    profit_margin: z.string().regex(/^-?\d{0,3}(?:\.\d{0,2})?$/),
    IVA: z.boolean().optional(),
    category: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    measurement_unit: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

export const zProductStockSaleWritable = z.object({
    stock: z.string().regex(/^-?\d{0,6}(?:\.\d{0,10})?$/)
});

/**
 * Serializador completo para Creación, Edición y Detalle
 */
export const zProductWriteDetailWritable = z.object({
    name: z.string().max(200),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    cost_price_usd: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/),
    profit_margin: z.string().regex(/^-?\d{0,3}(?:\.\d{0,2})?$/),
    IVA: z.boolean().optional(),
    category: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    measurement_unit: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    selling_units: z.array(zProductSellingUnit).optional()
});

export const zProviderWritable = z.object({
    name: z.string().max(200),
    phone: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    email: z.union([
        z.string().email().max(200),
        z.null()
    ]).optional(),
    document: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    changed_by: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

export const zRegisterUserRequestWritable = z.object({
    email: z.string().email().min(1).max(254),
    password: z.string().min(1).max(128),
    company_id: z.string().uuid(),
    branch_ids: z.array(z.string().uuid()).optional(),
    first_name: z.string().max(150).optional(),
    last_name: z.string().max(150).optional(),
    username: z.string().min(1).max(150).regex(/^[\w.@+-]+$/)
});

/**
 * Main serializer for creating and viewing sales.
 * Supports nested creation of sale details.
 */
export const zSaleWritable = z.object({
    branch: z.string().uuid(),
    customer: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

/**
 * Serializer for SaleDetail - used for reading sale details.
 * For writing, use the nested 'details' field in SaleSerializer.
 */
export const zSaleDetailWritable = z.object({
    product: z.string().uuid(),
    quantity: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/)
});

/**
 * Serializer for creating and viewing sale payments.
 * Handles currency conversion and payment status updates.
 */
export const zSalePaymentWritable = z.object({
    currency: z.string().max(3),
    payment_method: z.string(),
    discount: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/).optional()
});

/**
 * Serializer for creating and viewing sale payments.
 * Handles currency conversion and payment status updates.
 */
export const zSalePaymentRequestWritable = z.object({
    currency: z.string().min(1).max(3),
    payment_method: z.string().min(1),
    discount: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/).optional(),
    amount: z.string().regex(/^-?\d{0,8}(?:\.\d{0,2})?$/)
});

/**
 * Main serializer for creating and viewing sales.
 * Supports nested creation of sale details.
 */
export const zSaleRequestWritable = z.object({
    branch: z.string().uuid(),
    customer: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    details: z.array(z.record(z.unknown()))
});

export const zV1AccountsListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.number().int().optional(),
        page_size: z.number().int().optional()
    }).optional()
});

export const zV1AccountsListResponse = zPaginatedAccountListList;

export const zV1AccountsCreateData = z.object({
    body: zAccountRequestWritable,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1AccountsCreateResponse = zAccount;

export const zV1AccountsPaymentsListData = z.object({
    body: z.never().optional(),
    path: z.object({
        account_id: z.string()
    }),
    query: z.never().optional()
});

export const zV1AccountsPaymentsListResponse = z.array(zAccountPayment);

export const zV1AccountsPaymentsCreateData = z.object({
    body: zAccountPaymentRequestWritable,
    path: z.object({
        account_id: z.string()
    }),
    query: z.never().optional()
});

export const zV1AccountsPaymentsCreateResponse = zAccountPayment;

export const zV1AccountsDestroyData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * No response body
 */
export const zV1AccountsDestroyResponse = z.void();

export const zV1AccountsRetrieveData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1AccountsRetrieveResponse = zAccount;

export const zV1AccountsPartialUpdateData = z.object({
    body: zPatchedAccountRequestWritable.optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1AccountsPartialUpdateResponse = zAccount;

export const zV1AccountsUpdateData = z.object({
    body: zAccountRequestWritable,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1AccountsUpdateResponse = zAccount;

export const zV1BranchListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1BranchListResponse = z.array(zBranch);

export const zV1BranchCreateData = z.object({
    body: zBranchRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1BranchCreateResponse = zBranch;

export const zV1BranchDestroyData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * No response body
 */
export const zV1BranchDestroyResponse = z.void();

export const zV1BranchRetrieveData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1BranchRetrieveResponse = zBranch;

export const zV1BranchPartialUpdateData = z.object({
    body: zPatchedBranchRequest.optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1BranchPartialUpdateResponse = zBranch;

export const zV1BranchUpdateData = z.object({
    body: zBranchRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1BranchUpdateResponse = zBranch;

export const zV1CategoryListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1CategoryListResponse = z.array(zCategory);

export const zV1CategoryCreateData = z.object({
    body: zCategoryRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1CategoryCreateResponse = zCategory;

export const zV1CategoryDestroyData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * No response body
 */
export const zV1CategoryDestroyResponse = z.void();

export const zV1CategoryRetrieveData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1CategoryRetrieveResponse = zCategory;

export const zV1CategoryPartialUpdateData = z.object({
    body: zPatchedCategoryRequest.optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1CategoryPartialUpdateResponse = zCategory;

export const zV1CategoryUpdateData = z.object({
    body: zCategoryRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1CategoryUpdateResponse = zCategory;

export const zV1CompanyRetrieveData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1CompanyRetrieveResponse = zCompany;

export const zV1CompanyPartialUpdateData = z.object({
    body: zPatchedCompanyRequest.optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1CompanyPartialUpdateResponse = zCompany;

export const zV1CompanyCreateData = z.object({
    body: zCompanyRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1CompanyCreateResponse = zCompany;

export const zV1CompanyUpdateData = z.object({
    body: zCompanyRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1CompanyUpdateResponse = zCompany;

export const zV1CustomersListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1CustomersListResponse = z.array(zCustomer);

export const zV1CustomersCreateData = z.object({
    body: zCustomerRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1CustomersCreateResponse = zCustomer;

export const zV1CustomersDestroyData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * No response body
 */
export const zV1CustomersDestroyResponse = z.void();

export const zV1CustomersRetrieveData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1CustomersRetrieveResponse = zCustomer;

export const zV1CustomersPartialUpdateData = z.object({
    body: zPatchedCustomerRequest.optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1CustomersPartialUpdateResponse = zCustomer;

export const zV1CustomersUpdateData = z.object({
    body: zCustomerRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1CustomersUpdateResponse = zCustomer;

export const zV1ExchangeRatesRetrieveData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1ExchangeRatesHistoryRetrieveData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1ExchangeRatesTodayRetrieveData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1LoginCreateData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1LogoutCreateData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1MeasurementListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1MeasurementListResponse = z.array(zMeasurementUnit);

export const zV1MeasurementCreateData = z.object({
    body: zMeasurementUnitRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1MeasurementCreateResponse = zMeasurementUnit;

export const zV1MeasurementDestroyData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * No response body
 */
export const zV1MeasurementDestroyResponse = z.void();

export const zV1MeasurementRetrieveData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1MeasurementRetrieveResponse = zMeasurementUnit;

export const zV1MeasurementPartialUpdateData = z.object({
    body: zPatchedMeasurementUnitRequest.optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1MeasurementPartialUpdateResponse = zMeasurementUnit;

export const zV1MeasurementUpdateData = z.object({
    body: zMeasurementUnitRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1MeasurementUpdateResponse = zMeasurementUnit;

export const zV1ProductListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1ProductListResponse = z.array(zProductMaster);

export const zV1ProductCreateData = z.object({
    body: zProductWriteDetailRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1ProductCreateResponse = zProductWriteDetail;

export const zV1ProductBranchStockListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1ProductBranchStockListResponse = z.array(zProductStockSale);

export const zV1ProductDestroyData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * No response body
 */
export const zV1ProductDestroyResponse = z.void();

export const zV1ProductRetrieveData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1ProductRetrieveResponse = zProductWriteDetail;

export const zV1ProductPartialUpdateData = z.object({
    body: zPatchedProductWriteDetailRequest.optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1ProductPartialUpdateResponse = zProductWriteDetail;

export const zV1ProductUpdateData = z.object({
    body: zProductWriteDetailRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1ProductUpdateResponse = zProductWriteDetail;

export const zV1ProvidersListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1ProvidersListResponse = z.array(zProvider);

export const zV1ProvidersCreateData = z.object({
    body: zProviderRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1ProvidersCreateResponse = zProvider;

export const zV1ProvidersDestroyData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * No response body
 */
export const zV1ProvidersDestroyResponse = z.void();

export const zV1ProvidersRetrieveData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1ProvidersRetrieveResponse = zProvider;

export const zV1ProvidersPartialUpdateData = z.object({
    body: zPatchedProviderRequest.optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1ProvidersPartialUpdateResponse = zProvider;

export const zV1ProvidersUpdateData = z.object({
    body: zProviderRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1ProvidersUpdateResponse = zProvider;

export const zV1RefreshCreateData = z.object({
    body: zTokenRefreshRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1RefreshCreateResponse = zTokenRefresh;

export const zV1RegisterCreateData = z.object({
    body: zRegisterUserRequestWritable,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1RegisterCreateResponse = zRegisterUser;

export const zV1SalesListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.number().int().optional(),
        page_size: z.number().int().optional()
    }).optional()
});

export const zV1SalesListResponse = zPaginatedSaleListList;

export const zV1SalesCreateData = z.object({
    body: zSaleRequestWritable,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1SalesCreateResponse = zSale;

export const zV1SalesDestroyData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * No response body
 */
export const zV1SalesDestroyResponse = z.void();

export const zV1SalesRetrieveData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1SalesRetrieveResponse = zSale;

export const zV1SalesPartialUpdateData = z.object({
    body: zPatchedSaleRequestWritable.optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1SalesPartialUpdateResponse = zSale;

export const zV1SalesUpdateData = z.object({
    body: zSaleRequestWritable,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zV1SalesUpdateResponse = zSale;

export const zV1SalesPaymentsListData = z.object({
    body: z.never().optional(),
    path: z.object({
        sale_id: z.string()
    }),
    query: z.never().optional()
});

export const zV1SalesPaymentsListResponse = z.array(zSalePayment);

export const zV1SalesPaymentsCreateData = z.object({
    body: zSalePaymentRequestWritable,
    path: z.object({
        sale_id: z.string()
    }),
    query: z.never().optional()
});

export const zV1SalesPaymentsCreateResponse = zSalePayment;

export const zV1UserBranchesRetrieveData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1UserBranchesUpdateData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1UserInfoRetrieveData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1UserInfoRetrieveResponse = zCustomUser;

export const zV1UserInfoPartialUpdateData = z.object({
    body: zPatchedCustomUserRequest.optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1UserInfoPartialUpdateResponse = zCustomUser;

export const zV1UserInfoUpdateData = z.object({
    body: zCustomUserRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zV1UserInfoUpdateResponse = zCustomUser;
